### ISSUE TITLE
Email notifikace SMTP

### ISSUE THREAD

**Issue by lukyrys** [RoboZonky/robozonky#119]
Je moznost posilat notifikace bez overeni smtp? Mam klasicky relay na localhostu ktery nevyzaduje overeni ale robozonky se pokousi o overeni i presto ze mam zakomentovane radky 
Pak jsem narazil taky na problem kdy nastaveni requiresSslOnConnect zmeni natvrdo port na 465 (postrada pak smysl nastaveni smtp.port)
Pak bych se jeste rad zeptal jestli se pocita s implementaci TLS

**Comment by triceo** [comment]
Zdravím, toho času jsem na dovolené, budu se tomu tedy moci věnovat až v květnu. Prozatím pár poznámek:

- Někdo mi říkal, že to s lokálním SMTP serverem, tedy bez autentizace, používá. Že prý stačí prostě neuvést v konfiguraci jméno a heslo. Ale sám nevím, budu to muset vyzkoušet.
- `requiresSslOnConnect` by port měnit nemělo. Pokud se tak děje, je to chyba kterou bych opravil.
- Co se týká TLS, `smtp.requiresStartTLS = true`` by to mělo řešit.

**Comment by triceo** [comment]
@lukyrys, tak už bych se na to mohl podívat. Dvě otázky, než se do toho dám:

- Funguje to TLS tak, jak jsem popsal?
- Když necháš jméno i heslo prázdné (nikoliv zakomentované), funguje už to SMTP?

**Comment by triceo** [comment]
Skoro rok bez odezvy, zavírám.
