### ISSUE TITLE
Nová strategie (>=4.0.0) - parsování

### ISSUE THREAD

**Issue by LukasLedvina** [RoboZonky/robozonky#139]
Zjistil jsem, že na masterovi `ad922746` není dovoleno mít v popisu strategie dvě mezery za sebou. Nevím, zdali jde o feature nebo bug. Takže si není možno pěkně zformátovat pravidla. :-(

```
robozonky-strategy.cfg
Prostředky v ratingu A*  tvoří 3 až 7 % aktuální zůstatkové částky
```
```
11:00:30.373 INFO  ===== RoboZonky v4.0.0-SNAPSHOT at your service! =====
line 29:23 extraneous input ' ' expecting ' tvoří '
```

**Comment by triceo** [comment]
Dobrá poznámka. Podívám se na to.
