### ISSUE TITLE
Nová strategie: neintuitivní nastavení podílů ratingů v portfoliu

### ISSUE THREAD

**Issue by triceo** [RoboZonky/robozonky#141]
- Není dost zřejmé, že součet podílů musí dát dohromady 100 %.
- Example ve Wiki by měl skutečně fungovat jako strategie. :-)

**Comment by LukasLedvina** [comment]
Mě není moc zřejmé, jak se robot chová, pokud je podíl:

1. Pod dolní hranicí podílu (těch, co mají mít součet 100%),
2. mezi dolní a horní hranicí a
3. nad horní hranicí.

Ve třetím případě již nic nenakupuje, ale jak se liší chování v případě 1 a 2?

**Comment by triceo** [comment]
Nijak - v obou případech nakupuje. Rozdíl je jen v tom, v jakém pořadí dojde k nákupu. Nejdřív se budou nakupovat ty, které mají nejvíc pod dolní hranicí. A až poté, co žádný nemá pod dolní hranicí, může dojít na ty, co nemají pod horní hranicí.

Samozřejmě situace, že všechny ratingy jsou nad dolní hranicí, nikdy nenastane. Nicméně v situaci, kdy žádná půjčka v takovém ratingu na tržišti není, může být zainvestována půjčka, kde se rating pohybuje mezi dolní a horní hranicí.

Dolní a horní hranice jsou tedy prakticky k tomu, aby určovaly prioritu jednotlivých půjček na tržišti.

**Comment by triceo** [comment]
Nakonec tuhle issue zavírám, protože jediná správný formát strategie nyní řeší [konfigurátor strategie](https://robozonky.github.io/robozonky/konfigurace-strategie/).
