### ISSUE TITLE
Neintuitivní vyjádření ratingCondition v natural konfiguraci

### ISSUE THREAD

**Issue by jhrcek** [RoboZonky/robozonky#143]
Neintuitivní vyjádření podmínky ratingCondition v Tokens.g4:
"Rating je lepší než" má v češtině sémantiku >, ale generuje kód se sémantikou >=
Podobně u horší než. Navrhuju být více explicitní a použít "Rating je leší nebo roven". Alternativně "Rating je XYZ nebo lepší".

Např. "Rating je lepší než A**" nedává smysl v češtině, ale v konfiguraci strategie se z toho vytvoří semanticky validní  LoanRatingBetterOrEqualCondition

**Comment by triceo** [comment]
Všiml jsem si toho včera a taky jsem to včera fixnul. :-) Ale každopádně díky!

**Comment by triceo** [comment]
Nevyřešil. Teď koukám, že jsem zapomněl na "BetterOrEqual", ačkoliv "WorseOrEqual" už jsem předělal na "Worse". V podstatě nevidím důvod pro "OrEqual", protože to jde vždycky napsat jako "Better" nebo "Worse", posunutý o jeden rating. Takže to asi zruším a nechám čistě jen Better/Worse. Co Ty na to, @jhrcek ?

**Comment by triceo** [comment]
Opraveno. (34c2486401b854870b45fa0235660d56bd3c7fca)

**Comment by jhrcek** [comment]
Souhlasím se zrušením OrEqual.
