### ISSUE TITLE
Missing execution rights for robozonky.sh

### ISSUE THREAD

**Issue by jhrcek** [RoboZonky/robozonky#156]
After installing latest 4.1.0 snapshot via installer (mostly accepting defaults) and executing

```
./run.sh 
./run.sh: line 4: /home/hrk/Tools/robozonky/Dist/robozonky.sh: Permission denied
```

I could work around that by by granting execute permission for robozonky.sh to my user.

**Comment by triceo** [comment]
Interesting. There's code in there that does exactly that. :-) I'll take a look, thanks for reporting!
