### ISSUE TITLE
Kompatibilita strategie s robotem

### ISSUE THREAD

**Issue by triceo** [RoboZonky/robozonky#163]
Potřebujeme vyřešit, jak se vyrovnat s touhle situací:

- Uživatel běží robota verze X.
- Webový generátor strategie obsahuje nové vlastnosti, dostupné pouze v robotovi verze X+1.
- Uživatel si vygeneruje novou strategii na webu, ale neupgraduje robota. To vyústí ve velmi kryptický syntax error.

Vidím několik možností:

1. Generátor bude umět vyrobit strategii volitelně pro všechny verze.
2. _RoboZonky_ bude mít více parserů pro různé verze, a autodetekci správného parseru.
3. Ve strategii vynutíme nějakou direktivou minimální verzi. Uživatel pořád dostane výjimku, ale ta výjimka bude hezčí - upozorní, že je potřeba aktualizovat robota. V tomhle případě musíme i vymyslet, jestli tu direktivu udělat povinnou (a okamžitě tím rozbít roboty všem lidem na verzi 4.0.x) nebo volitelnou, a jak reagovat v případě, kdy chybí.

Co myslíš, @jhrcek ?

**Comment by jhrcek** [comment]
1. je něco co bych nerad implementoval. Bylo by to možné, ale ve srovnání se (žádoucí) migrací uživatele na nejnovější verzi robota zbytečná práce navíc.
2. se mi zdá jako obdoba 1. implementovaná na straně robota
3. mi příjde jako nejschůdnější - nejjednodušší. Několik myšlenek:

* pokud nevynutíme povinnou direktivu specifikující minimalní potřebnou verzi robota, museli bychom být schopni rozlišit parse errory způsobené validní strategií obsahující nové features a strategií, která nejde parsovat z jiných důvodu. Potenciálně můžeme při parse erroru VŽDY vypsat. "Nepodařilo se přečíst strategii. Používáte nejnovější verzi robozonky 4.0.1? ... konkrétní chyba"
* při použití nové konfigurace strategie se starým robotem dostane uživatel useles parse error každopádně, bez ohledu jestli tam tu verzi dáme nebo ne.

**Comment by jhrcek** [comment]
Tohle je něco, co by bylo vhodné vyřešit asap - využít toho, že lidi si asi stejně budou chtit aktualizovat robota na nejnovější verzi kvůli změnám v zonky api a udělat supported.robozonky.version povinnou součásti strategie. @triceo co myslíš?

**Comment by triceo** [comment]
@jhrcek Když jinak nedáš. :-) OK, aktualizuj ten svůj nový pull request. Viděl bych to takhle:

- Do sekce "Obecná nastavení" dogeneruj "Tato strategie vyžaduje RoboZonky 4.1.0 nebo pozdější."
- Já to mezitím nějak zkusím naimplementovat.

**Comment by triceo** [comment]
Drobná změna. Řádek "Tato strategie vyžaduje RoboZonky 4.1.0 nebo pozdější." bude první řádek souboru (na komentářích nezáleží).

**Comment by triceo** [comment]
@jhrcek Prohlídni si, prosím, ten comment výše - finální implementace lepší než tisíc specifikací. :-) Zavřu to tu, až bude pull request pro web.

**Comment by jhrcek** [comment]
Ok, přidal jsem [řádek s deklarací požadované verze](https://github.com/RoboZonky/natural-strategy-setup/commit/6973a2aad844d6260aad11f27dbe222f767ab4cf) a aktualizoval jsem PR.

**Comment by triceo** [comment]
Díky!
