### ISSUE TITLE
Notifikace o nákupu na sekundárním trhu má špatný počet zbývajících splátek

### ISSUE THREAD

**Issue by v6ak** [RoboZonky/robozonky#165]
Došel mi e-mail, u kterého jsem si říkal, že to nemělo projít mým filtrem. Pak jsem ale zjistil, že počet splátek je celkový počet splátek, ne zbývající.

Chyba bude patrně v https://github.com/RoboZonky/robozonky/blob/master/robozonky-notifications/src/main/resources/com/github/robozonky/notifications/email/investment-purchased.ftl , kde to čte loanTerm (což asi bude celková doba půjčky).

**Comment by triceo** [comment]
Díky za nahlášení! Opravím to při příští příležitosti.
