### ISSUE TITLE
RoboZonky v Dockeru

### ISSUE THREAD

**Issue by triceo** [RoboZonky/robozonky#178]
Jednolitá distribuce pro všechny operační systémy. A v budoucnosti (po #112) s pomocí JLinku snad i integrované, customizované JRE.

**Comment by triceo** [comment]
Pro pozdější referenci: https://hub.docker.com/_/openjdk/

**Comment by marek-stopka** [comment]
@triceo, jsou v repozitáři nějaké soubory, které by se měly přidat do .dockerignore? Tedy soubory, které nejsou potřeba k buildu RoboZonky, ani k jeho běhu...

**Comment by marek-stopka** [comment]
@triceo, prosím asigni issue na mě, navíc image má po buildu přes 1,2GB:

    urberi:robozonky marekstopka$ docker images
    REPOSITORY                    TAG                 IMAGE ID            CREATED             SIZE
    <none>                        <none>              1d7ea5d8cd4b        3 minutes ago       1.26GB

Můžu z toho odstranit zdrojáky a `maven` cache? Jak nejlépe odstranit maven cache (`/root` má přes 300MB)?

Našel jsem [tohle](https://stackoverflow.com/a/22671261/858183), chápu to správně, že `mvn dependency:purge-local-repository -DactTransitively=false -DreResolve=false --fail-at-end
` je nejlepší možnost jak se těch přebytečných dat zbavit? Chceš tam nějakou IF možnost, aby si to případně mohl ten clean-up jednoduše pro troubleshooting vypnout (bude to vypadat prasácky, ale napsat to lze stando a ty budeš jen muset přidat option k `docker build` příkazu)?

**Comment by triceo** [comment]
Pro zmenšení binárky doporučuju dvě věci:

* Maven do ${USER_HOME}/.m2 stáhnul půl internetu. Smazat.
* Spustit `mvn clean` v rootu RoboZonky. (Ale až poté, co sis nějak zpracoval ten ZIP.) Proč vlastně nesmazat celý ten adresář se zdrojáky? Po buildu už není potřeba.

Jinak co jsem se díval, tak oficiální OpenJDK image je postavená na nějakém Alpine Linuxu, který je orientovaný na to, aby byl co nejmenší. Tuším že má jen několik málo megabytů. Bylo by sympatické někdy v budoucnosti zmigrovat.

**Comment by triceo** [comment]
Myslím, že v rámci toho Docker image nebudu potřebovat žádná ladicí data. Jestli se ten docker image bude buildovat sám s každým commitem nebo s každým releasem, tak si všechno zvládnu poladit mimo ten image v rámci standardního Maven buildu.

**Comment by triceo** [comment]
Docker images odteď automaticky dostupné tady:
https://hub.docker.com/r/robozonky/robozonky

Buildují se pro:
- Každou změnu na masteru.
- Každou změnu na release brancích.
- Každý release tag.

Parametry image:
- Postaveno na `fedora:latest`.
- Používá poslední dostupnou verzi balíku `java-openjdk`, v tuhle chvíli tedy Javu 10.

Ukázka spuštění na masteru:
`docker run -it -v ${LOCAL_CFG_DIR}:/etc/robozonky -v ${LOCAL_WORKING_DIR}:/var/robozonky robozonky:dev`
