### ISSUE TITLE
Strategie - nefungujici filtrovani

### ISSUE THREAD

**Issue by Marfusios** [RoboZonky/robozonky#181]
Dobry den,

dekuji moc za robota, funguje perfektne. 
Jediny problem, ktery jsem vypozoroval v aktualni verzi je, ze se mi neaplikuje filtrovani nastavene ve strategii. 

Strategie: 
```
# Konfigurace strategie vytvořená 22.11.2017 nástrojem natural-strategy-setup verze ef43711
Tato strategie vyžaduje RoboZonky ve verzi 4.1.0 nebo pozdější.
- Obecná nastavení
Robot má udržovat progresivní portfolio.
Běžná výše investice je 200 až 400 Kč.
Investovat maximálně 2 % výše úvěru.

- Filtrování tržiště
Ignorovat úvěr, kde: délka přesahuje 49 měsíců.
Ignorovat participaci, kde: délka přesahuje 49 měsíců.
```

A robot stejne zainvestoval do pujcky [na 84 mesicu](https://app.zonky.cz/jine/hci-pro-sebe-a-manzelku-hezky-domov-171243) 

V logu jsem nasel toto:
`10:36:27.056 [rzBackground-thread-1] DEBUG c.g.r.s.n.NaturalLanguageStrategyService Cached strategy: ParsedStrategy{defaults=DefaultValues{portfolio=PROGRESSIVE, targetPortfolioSize=2147483647, minimumBalance=200, investmentSize=DefaultInvestmentSize{minimumInvestmentInCzk=200, maximumInvestmentInCzk=400}, investmentShare=DefaultInvestmentShare{minimumShareInPercent=0, maximumShareInPercent=2}, confirmationCondition=com.github.robozonky.strategy.natural.DefaultValues$1@15be46}, investmentSizes={}, minimumVersion=4.1.0, portfolio={}, primaryMarketplaceFilters=[MarketplaceFilter (#1: [LoanTermCondition (Range: <50; 84>.)] but not [].)], secondaryMarketplaceFilters=[MarketplaceFilter (#2: [LoanTermCondition (Range: <50; 84>.)] but not [].)], sellFilters=[]}.
`

Mam nekde neco spatne nastavene?

**Comment by triceo** [comment]
Díky za report, podívám se na to do konce týdne.

**Comment by triceo** [comment]
@Marfusios Můžete, prosím, poslat větší kus logu? Zběžně jsem se na to podíval - stejná strategie, stejná půjčka, nicméně správný výsledek. Půjčka byla zamítnuta.

**Comment by Marfusios** [comment]
Jiste, [odkaz](https://gist.github.com/Marfusios/4b287bf044942574f2bdb210e0d981d6)

Dale jsem vyzkousel zvolit primo rozsah 49-84, bohuzel jeste horsi vysledek: [log](https://gist.github.com/Marfusios/4622b6f5156cb404e6e8143840d6e9da)
Strategie:
```
# Konfigurace strategie vytvořená 22.11.2017 nástrojem natural-strategy-setup verze ef43711
Tato strategie vyžaduje RoboZonky ve verzi 4.1.0 nebo pozdější.
- Obecná nastavení
Robot má udržovat progresivní portfolio.
Běžná výše investice je 200 až 400 Kč.
Investovat maximálně 2 % výše úvěru.

- Filtrování tržiště
Ignorovat úvěr, kde: délka je 49 až 84 měsíců.
Ignorovat participaci, kde: délka je 49 až 84 měsíců.
```

Robozonky 4.1.2 (dnes stahnute, pouzival jsem predtim verzi 3.x, kterou jsem ale pred instalaci smazal)
Windows 10 
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) Client VM (build 25.131-b11, mixed mode, sharing)

**Comment by triceo** [comment]
Přiznám se, že jsem poněkud zmatený. 

Pročetl jsem si oba logy z předchozího komentáře a ani v jednom z nich není ani stopy po nějaké investici. Pokud robot něco investoval, pak o tom nic nenapsal do logu, což se nemůže stát - takže leda by šlo o logy z jiné doby.

K mému zmatení přispívá i poznámka "bohužel ještě horší výsledek" - po ní totiž následuje odkaz na log, ve kterém robot neudělal zhola nic. Jen se přihlásil a průběžně kontrolovat tržiště.

**Comment by Marfusios** [comment]
Horsim vysledkem jsem myslel tu cast, kde se mu ani nepodarilo rozparsovat tu strategii:
```
11:05:13.463 [rzBackground-thread-1] DEBUG c.g.r.s.n.NaturalLanguageStrategyService Failed parsing strategy, OK if using different: Syntax error: <unknown>:2:43: line 2:43 mismatched input '4' expecting {'Tato strategie vyžaduje RoboZonky ve verzi ', 'Robot má udržovat ', '- '}, offending symbol: [@0,136:136='4',<107>,2:43].
```
Pouzil jsem primo tu vygenerovanou z webu. Pouze jsem zmenil priponu `txt` na `cfg`. 

Co se tyce investici, tak notifikace normalne prisla na email: 
![image](https://user-images.githubusercontent.com/3494837/33151389-2e80862a-cfd8-11e7-862c-921a3acfcec1.png)

A v systemu: 
![image](https://user-images.githubusercontent.com/3494837/33151416-544aa9f8-cfd8-11e7-8630-6f8e23918ef8.png)

Zkusim to tedy radeji preinstalovat jeste jednou, ale musim pockat az se mi pripise novy vklad.

**Comment by triceo** [comment]
Aha, chyba ve čtení strategie - to jsem přehlédl. To je ještě zajímavější než předtím.
Doporučuji chvíli používat robota s přepínačem "-d" - nebude nic investovat, ale bude se chovat jako by investoval, takže půjde sledovat, jestli se taková chyba ještě objeví.

**Comment by triceo** [comment]
@Marfusios Ne, tohle je v pořádku - jedná se o filtr, takže ta podmínka je obrácená. Když platí, tak se půjčka bude ignorovat. Zatím nevím, co přesně je špatně, ale budu to hledat.

**Comment by Marfusios** [comment]
Ok. 
Nejsem moc zbehly v Jave, ale na prvni pohled bych rekl, ze tady ty dva radky ([71](https://github.com/RoboZonky/robozonky/blob/f87f2d797bfbdcd42142e216ead481756ebc571a/robozonky-strategy-natural/src/main/antlr4/imports/CommonFilters.g4#L71) a [76](https://github.com/RoboZonky/robozonky/blob/f87f2d797bfbdcd42142e216ead481756ebc571a/robozonky-strategy-natural/src/main/antlr4/imports/CommonFilters.g4#L76)) by mely byt prohozene v pripade, ze chceme filtrovat/ignorovat. Potom ta metoda [test](https://github.com/RoboZonky/robozonky/blob/master/robozonky-strategy-natural/src/main/java/com/github/robozonky/strategy/natural/conditions/RangeCondition.java#L49) to bere vzdy jako inkluzivni rozsah.

**Comment by triceo** [comment]
Vidím tady dva různé problémy:

- Jednak že za nějakých okolností, které se mi zatím nepodařilo vystopovat, nefunguje filtr.
- Druhak že za nějakých okolností nejde přečíst jinak platnou strategii.

V tuhle chvíli budu řešit ten druhý, protože nějaká chyba na tomhle místě by možná mohla způsobit chybu filtru. Můžete mi, prosím, poslat tu strategii, která nefungovala? A tentokrát myslím celý ten konkrétní soubor, nikoliv jeho obsah. Zkoušel jsem už snad tisíc způsobů, jak parser rozbít, a nepodařilo se - takže to musí být něco konkrétního ve Vašem souboru. Bílé znaky nebo něco takového, co se přepisem sem na Github ztratí.

**Comment by triceo** [comment]
Už jsem na to přišel! 

Existují v podstatě tři druhy značení konce řádku: `\n` na Unixu, `\r\n` na Windows a `\r` na prehistorickém Macu. Nevím, jak jste to udělal, ale do Vaší strategie jste propašoval právě to poslední - to jediné, co parser nezvládal. :-)

Nicméně s filtry to nemá nic společného, takže zpátky k původnímu problému.

**Comment by Marfusios** [comment]
Podarilo se mi to rozjet. Mel jste dobry napad, ze to bude neco s formatovanim. Problem, ale nebylo line endings (funguje jak win, tak unix, v chybne strategii jsem pouzival win - \r\n). 
Spatne parsovani zpusobilo kodovani, mel jsem nastaveny ANSI, po zmene na UTF-8 vse zacalo fungovat (nezavisle na konci radku, zkousel jsem obe moznosti). 

Soubory se strategii jsou nasdileny [tady](https://1drv.ms/f/s!AteY9NhsVotqlM4q5IZnnGHKGBinhQ)

**Comment by triceo** [comment]
Tak jsem strávil několik hodin uvnitř kódu strategie, prošel jsem to třikrát tam a zpátky, a žádnou chybu tam nevidím. Vaše strategie se, když do ní zadám stejná data, chová správně. Půjčku, kterou jste zmínil, mi odmítne.

To neznamená, že tam chyba není. Jenom budu potřebovat další data - takže pokud Vám robot příště udělá něco, co nemá, pošlete sem prosím log. Každá špetka informací navíc pomůže, bude to něco záludného.

**Comment by Marfusios** [comment]
Dekuji za snahu a pomoc. Dam te strategii jeste priste sanci a uvidime, mozna to byla jen nejaka shoda nahod (investoval jsem po dlouhe dobe). 

Jinak ta druha strategie (od-do) funguje bez problemu. Dnes zainvestovalo do 13 pujcek, vsechny pod 49 mesicu.

**Comment by triceo** [comment]
@Marfusios Právě jsem dodělal #185. Řeší to problém, kde se robot nechoval podle strategie. Ale projevovalo se to úplně jinak, než tohle, takže se Vás to nejspíš netýká. :-( Každopádně během pár dní vydám verzi 4.2.0, která bude mít alespoň tuhle opravu.

**Comment by triceo** [comment]
Podle neaktivity soudím, že problém již neexistuje. Zavírám. Pokud by se to znovu objevilo, neváhejte se ozvat.

**Comment by Marfusios** [comment]
Po delsi dobe jsem se dostal k instalaci nove verze (4.3.3) a bohuzel vypada, ze je porad stejny problem se zpracovanim strategie. 
Strategii jsem vygeneroval uplne novou, pomoci web konfiguratoru. 

Investovano do pujcky s delkou 84 mesicu: 
![image](https://user-images.githubusercontent.com/3494837/36781458-34edf2d2-1c76-11e8-949b-dc0efb7351d6.png)

Strategie:
```
# Konfigurace strategie vytvořená 28.2.2018 nástrojem natural-strategy-setup verze 29ee55d
Tato strategie vyžaduje RoboZonky ve verzi 4.3.0 nebo pozdější.
- Obecná nastavení
Robot má udržovat progresivní portfolio.
Běžná výše investice je 200 Kč.

- Filtrování tržiště
Ignorovat vše, kde: klient je důchodce; délka je 49 až 84 měsíců.
Prodej participací zakázán.
```

[Cely log](https://gist.github.com/Marfusios/303adedbb03caae8e787a2e136ba85ba)

**Comment by triceo** [comment]
Díky za dodatečné informace! Na první pohled tam nevidím nic zvláštního, ale budu se tomu věnovat.

**Comment by triceo** [comment]
Dobrý den, @Marfusios. Nejedná se o chybu.

Ve strategii máte následující: 

    Ignorovat vše, kde: klient je důchodce; délka je 49 až 84 měsíců.

Jinými slovy: robot bude ignorovat vše delší než 48 měsíců, kde ZÁROVEŇ klient je důchodce. Tato podmínka skutečně nebyla v půjčce #217693 splněna, protože klient je zaměstnanec. Robot tedy správně investoval.

Chcete-li ignorovat všechny důchodce i všechny půjčky přes 48 měsíců, potřebujete dvě nezávislá pravidla:

    Ignorovat vše, kde: klient je důchodce.
    Ignorovat vše, kde: délka je 49 až 84 měsíců.

**Comment by Marfusios** [comment]
Ah, chapu, diky za nalezeni problemu. 
Chtelo by to nejaky zpusobem podchytit v web konfiguratoru.

**Comment by triceo** [comment]
@Marfusios Máte pravdu. Už o tom nějaký čas přemýšlím, mate to více lidí.
