### ISSUE TITLE
RoboZonky nefunguje s OpenJDK 8 na MIPS platformě

### ISSUE THREAD

**Issue by marek-stopka** [RoboZonky/robozonky#184]
Dobrý den, zkouším se rozchodit RoboZonky na AsusWRT platformě (MIPS) s OpenJDK 8 a při spuštění to vypisuje následující chybu:

    admin@RT-N66U-2AB8:/tmp/mnt/sdb1/optware-ng/RoboZonky/4.1.2# ./robozonky-exec.sh 
    OpenJDK Zero VM warning: No monotonic clock was available - timed services may be adversely 
    affected if the time-of-day clock changes
    #
    # A fatal error has been detected by the Java Runtime Environment:
    #
    #  Internal Error (cppInterpreter_zero.cpp:812), pid=4124, tid=0x2b605510
    #  Error: Unimplemented()
    #
    # JRE version:  (8.0_102-b02) (build )
    # Java VM: OpenJDK Zero VM (25.102-b02 interpreted mode linux-mipsel )
    # Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
    #
    # An error report file with more information is saved as:
    # /tmp/mnt/sdb1/optware-ng/RoboZonky/4.1.2/hs_err_pid4124.log
    #
    # If you would like to submit a bug report, please visit:
    #   http://bugreport.java.com/bugreport/crash.jsp
    #
    Aborted

Ve zmíněném logu jsou následující informace:

    #
    # A fatal error has been detected by the Java Runtime Environment:
    #
    #  Internal Error (cppInterpreter_zero.cpp:812), pid=4124, tid=0x2b605510
    #  Error: Unimplemented()
    #
    # JRE version:  (8.0_102-b02) (build )
    # Java VM: OpenJDK Zero VM (25.102-b02 interpreted mode linux-mipsel )
    # Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
    #
    # If you would like to submit a bug report, please visit:
    #   http://bugreport.java.com/bugreport/crash.jsp
    #
    
    ---------------  T H R E A D  ---------------
    
    Current thread (0x0041c758):  JavaThread "Unknown thread" [_thread_in_vm, id=4125, stack(0x2b487000,0x2b606000)]
    
    Stack: [0x2b487000,0x2b606000],  sp=0x2b604900,  free space=1526k
    
    ---------------  P R O C E S S  ---------------
    
    Java Threads: ( => current thread )
    
    Other Threads:
    
    =>0x0041c758 (exited) JavaThread "Unknown thread" [_thread_in_vm, id=4125, stack(0x2b487000,0x2b606000)]
    
    VM state:not at safepoint (not fully initialized)
    
    VM Mutex/Monitor currently owned by a thread: None
    
    GC Heap History (0 events):
    No events
    
    Deoptimization events (0 events):
    No events
    
    Internal exceptions (0 events):
    No events
    
    Events (0 events):
    No events
    
    
    Dynamic libraries:
    00400000-00401000 r-xp 00000000 08:11 8328       /tmp/mnt/sdb1/optware-ng/lib/jvm/openjdk8/jre/bin/java
    00410000-00411000 rw-p 00000000 08:11 8328       /tmp/mnt/sdb1/optware-ng/lib/jvm/openjdk8/jre/bin/java
    00411000-00475000 rwxp 00411000 00:00 0          [heap]
    2aaa8000-2aaaf000 r-xp 00000000 08:11 8138       /tmp/mnt/sdb1/optware-ng/lib/ld-uClibc-1.0.26.so
    2aaaf000-2aab1000 rw-p 2aaaf000 00:00 0 
    2aab1000-2aab2000 r--p 2aab1000 00:00 0 
    2aab2000-2aaba000 rw-s 00000000 00:0a 3112252    /tmp/hsperfdata_admin/4124
    2aabe000-2aabf000 r--p 00006000 08:11 8138       /tmp/mnt/sdb1/optware-ng/lib/ld-uClibc-1.0.26.so
    2aabf000-2aac0000 rw-p 00007000 08:11 8138       /tmp/mnt/sdb1/optware-ng/lib/ld-uClibc-1.0.26.so
    2aac0000-2ab9f000 r-xp 00000000 08:11 8301       /tmp/mnt/sdb1/optware-ng/lib/libiconv.so.2.5.0
    2ab9f000-2abaf000 ---p 2ab9f000 00:00 0 
    2abaf000-2abb0000 rw-p 000df000 08:11 8301       /tmp/mnt/sdb1/optware-ng/lib/libiconv.so.2.5.0
    2abb0000-2abc8000 r-xp 00000000 08:11 8169       /tmp/mnt/sdb1/optware-ng/lib/libz.so.1.2.8
    2abc8000-2abd7000 ---p 2abc8000 00:00 0 
    2abd7000-2abd8000 rw-p 00017000 08:11 8169       /tmp/mnt/sdb1/optware-ng/lib/libz.so.1.2.8
    2abd8000-2abe7000 r-xp 00000000 08:11 8392       /tmp/mnt/sdb1/optware-ng/lib/jvm/openjdk8/jre/lib/mipsel/jli/libjli.so
    2abe7000-2abf7000 ---p 2abe7000 00:00 0 
    2abf7000-2abf8000 rw-p 0000f000 08:11 8392       /tmp/mnt/sdb1/optware-ng/lib/jvm/openjdk8/jre/lib/mipsel/jli/libjli.so
    2abf8000-2accd000 r-xp 00000000 08:11 8133       /tmp/mnt/sdb1/optware-ng/lib/libuClibc-1.0.26.so
    2accd000-2acdc000 ---p 2accd000 00:00 0 
    2acdc000-2acdd000 r--p 000d4000 08:11 8133       /tmp/mnt/sdb1/optware-ng/lib/libuClibc-1.0.26.so
    2acdd000-2acdf000 rw-p 000d5000 08:11 8133       /tmp/mnt/sdb1/optware-ng/lib/libuClibc-1.0.26.so
    2acdf000-2acf6000 rw-p 2acdf000 00:00 0 
    2acf6000-2b252000 r-xp 00000000 08:11 8362       /tmp/mnt/sdb1/optware-ng/lib/jvm/openjdk8/jre/lib/mipsel/server/libjvm.so
    2b252000-2b262000 ---p 2b252000 00:00 0 
    2b262000-2b288000 rw-p 0055c000 08:11 8362       /tmp/mnt/sdb1/optware-ng/lib/jvm/openjdk8/jre/lib/mipsel/server/libjvm.so
    2b288000-2b298000 rw-p 2b288000 00:00 0 
    2b298000-2b416000 r-xp 00000000 08:11 8158       /tmp/mnt/sdb1/optware-ng/lib/libstdc++.so.6.0.24
    2b416000-2b426000 ---p 2b416000 00:00 0 
    2b426000-2b431000 r--p 0017e000 08:11 8158       /tmp/mnt/sdb1/optware-ng/lib/libstdc++.so.6.0.24
    2b431000-2b434000 rw-p 00189000 08:11 8158       /tmp/mnt/sdb1/optware-ng/lib/libstdc++.so.6.0.24
    2b434000-2b436000 rw-p 2b434000 00:00 0 
    2b436000-2b43a000 r-xp 00000000 08:11 8276       /tmp/mnt/sdb1/optware-ng/lib/libffi.so.6.0.4
    2b43a000-2b449000 ---p 2b43a000 00:00 0 
    2b449000-2b44a000 rw-p 00003000 08:11 8276       /tmp/mnt/sdb1/optware-ng/lib/libffi.so.6.0.4
    2b44a000-2b476000 r-xp 00000000 08:11 8137       /tmp/mnt/sdb1/optware-ng/lib/libgcc_s.so.1
    2b476000-2b485000 ---p 2b476000 00:00 0 
    2b485000-2b486000 rw-p 0002b000 08:11 8137       /tmp/mnt/sdb1/optware-ng/lib/libgcc_s.so.1
    2b486000-2b48a000 ---p 2b486000 00:00 0 
    2b48a000-2b606000 rw-p 2b48a000 00:00 0 
    2b606000-2b611000 r-xp 00000000 08:11 8355       /tmp/mnt/sdb1/optware-ng/lib/jvm/openjdk8/jre/lib/mipsel/libverify.so
    2b611000-2b621000 ---p 2b611000 00:00 0 
    2b621000-2b622000 rw-p 0000b000 08:11 8355       /tmp/mnt/sdb1/optware-ng/lib/jvm/openjdk8/jre/lib/mipsel/libverify.so
    2b622000-2b657000 r-xp 00000000 08:11 8359       /tmp/mnt/sdb1/optware-ng/lib/jvm/openjdk8/jre/lib/mipsel/libjava.so
    2b657000-2b667000 ---p 2b657000 00:00 0 
    2b667000-2b668000 rw-p 00035000 08:11 8359       /tmp/mnt/sdb1/optware-ng/lib/jvm/openjdk8/jre/lib/mipsel/libjava.so
    2b668000-2b670000 r-xp 00000000 08:11 8360       /tmp/mnt/sdb1/optware-ng/lib/jvm/openjdk8/jre/lib/mipsel/libzip.so
    2b670000-2b67f000 ---p 2b670000 00:00 0 
    2b67f000-2b680000 rw-p 00007000 08:11 8360       /tmp/mnt/sdb1/optware-ng/lib/jvm/openjdk8/jre/lib/mipsel/libzip.so
    2b680000-2b6a8000 rwxp 2b680000 00:00 0 
    2b6a8000-2d680000 ---p 2b6a8000 00:00 0 
    2d680000-2d681000 rw-p 2d680000 00:00 0 
    2d681000-2d700000 ---p 2d681000 00:00 0 
    2d700000-2d701000 ---p 2d700000 00:00 0 
    2d701000-2d780000 rw-p 2d701000 00:00 0 
    2d780000-2d781000 ---p 2d780000 00:00 0 
    2d781000-2d800000 rw-p 2d781000 00:00 0 
    2d800000-2d801000 ---p 2d800000 00:00 0 
    2d801000-2d883000 rw-p 2d801000 00:00 0 
    2d883000-2d8e0000 ---p 2d883000 00:00 0 
    2d8e0000-2d8e3000 rw-p 2d8e0000 00:00 0 
    2d8e3000-2d910000 ---p 2d8e3000 00:00 0 
    2d910000-2d913000 rw-p 2d910000 00:00 0 
    2d913000-2d940000 ---p 2d913000 00:00 0 
    2d940000-2d941000 ---p 2d940000 00:00 0 
    2d941000-2d9e0000 rw-p 2d941000 00:00 0 
    2da00000-2e000000 rw-p 2da00000 00:00 0 
    2e000000-33a00000 ---p 2e000000 00:00 0 
    33a00000-33a18000 rw-p 33a00000 00:00 0 
    33a18000-33b80000 ---p 33a18000 00:00 0 
    33b80000-33b98000 rw-p 33b80000 00:00 0 
    33b98000-33d00000 ---p 33b98000 00:00 0 
    33d00000-33d01000 ---p 33d00000 00:00 0 
    33d01000-33d80000 rw-p 33d01000 00:00 0 
    33d80000-341cc000 ---p 33d80000 00:00 0 
    341cc000-34227000 rw-p 341cc000 00:00 0 
    7ff2e000-7ff43000 rwxp 7ff2e000 00:00 0          [stack]
    7fff7000-7fff8000 r-xp 7fff7000 00:00 0          [vdso]
    
    VM Arguments:
    jvm_args: -XX:+UseG1GC -Drobozonky.properties.file=/opt/RoboZonky/4.1.2/robozonky.properties -Dcom.sun.management.jmxremote=false -Dlogback.configurationFile=/opt/RoboZonky/4.1.2/logback.xml -Dfile.encoding=UTF-8 -Djava.net.preferIPv4Stack=true 
    java_command: /opt/RoboZonky/4.1.2/Dist/bin/robozonky-app-4.1.2.jar @/opt/RoboZonky/4.1.2/robozonky.cli
    java_class_path (initial): /opt/RoboZonky/4.1.2/Dist/bin/robozonky-app-4.1.2.jar
    Launcher Type: SUN_STANDARD
    
    Environment Variables:
    JAVA_HOME=
    PATH=/bin:/usr/bin:/sbin:/usr/sbin:/home/admin:/mmc/sbin:/mmc/bin:/mmc/usr/sbin:/mmc/usr/bin:/opt/sbin:/opt/bin:/opt/usr/sbin:/opt/usr/bin
    SHELL=/bin/sh
    
    Signal Handlers:
    SIGSEGV: [libjvm.so+0x4df4f0], sa_mask[0]=11111111011111111111110111111110, sa_flags=SA_RESTART|SA_SIGINFO
    SIGBUS: [libjvm.so+0x4df4f0], sa_mask[0]=11111111011111111111110111111110, sa_flags=SA_RESTART|SA_SIGINFO
    SIGFPE: [libjvm.so+0x3e5350], sa_mask[0]=11111111011111111111110111111110, sa_flags=SA_RESTART|SA_SIGINFO
    SIGPIPE: [libjvm.so+0x3e5350], sa_mask[0]=11111111011111111111110111111110, sa_flags=SA_RESTART|SA_SIGINFO
    SIGXFSZ: [libjvm.so+0x3e5350], sa_mask[0]=11111111011111111111110111111110, sa_flags=SA_RESTART|SA_SIGINFO
    SIGILL: [libjvm.so+0x3e5350], sa_mask[0]=11111111011111111111110111111110, sa_flags=SA_RESTART|SA_SIGINFO
    SIGUSR1: SIG_DFL, sa_mask[0]=00000000000000000000000000000000, sa_flags=none
    SIGUSR2: [libjvm.so+0x3e4fac], sa_mask[0]=00000000000000000000000000000000, sa_flags=SA_RESTART|SA_SIGINFO
    SIGHUP: SIG_DFL, sa_mask[0]=00000000000000000000000000000000, sa_flags=none
    SIGINT: SIG_DFL, sa_mask[0]=00000000000000000000000000000000, sa_flags=none
    SIGTERM: SIG_DFL, sa_mask[0]=00000000000000000000000000000000, sa_flags=none
    SIGQUIT: SIG_DFL, sa_mask[0]=00000000000000000000000000000000, sa_flags=none
    
    
    ---------------  S Y S T E M  ---------------
    
    OS:Linux
    uname:Linux 2.6.22.19 #1 Wed Oct 4 15:00:45 EDT 2017 mips
    libc:2 NPTL 1.0.26 
    rlimit: STACK 8192k, CORE 0k, NPROC 2047, NOFILE 1024, AS infinity
    load average:0.47 0.32 0.72
    
    /proc/meminfo:
    MemTotal:       239672 kB
    MemFree:        159532 kB
    Buffers:          1588 kB
    Cached:          42472 kB
    SwapCached:          4 kB
    Active:          39376 kB
    Inactive:        15172 kB
    HighTotal:      131072 kB
    HighFree:        73568 kB
    LowTotal:       108600 kB
    LowFree:         85964 kB
    SwapTotal:      524280 kB
    SwapFree:       523696 kB
    Dirty:              28 kB
    Writeback:           0 kB
    AnonPages:       10508 kB
    Mapped:           9464 kB
    Slab:            17188 kB
    SReclaimable:     2092 kB
    SUnreclaim:      15096 kB
    PageTables:        652 kB
    NFS_Unstable:        0 kB
    Bounce:              0 kB
    CommitLimit:    644116 kB
    Committed_AS:    33420 kB
    VmallocTotal:  1015800 kB
    VmallocUsed:      6656 kB
    VmallocChunk:  1006968 kB
    
    
    CPU:total 1 
    
    /proc/cpuinfo:
    system type        : Broadcom BCM5300 chip rev 1 pkg 0
    processor        : 0
    cpu model        : MIPS 74K V4.9
    BogoMIPS        : 299.82
    wait instruction    : no
    microsecond timers    : yes
    tlb_entries        : 64
    extra interrupt vector    : no
    hardware watchpoint    : yes
    ASEs implemented    : mips16 dsp
    shadow register sets    : 1
    VCED exceptions        : not available
    VCEI exceptions        : not available
    
    unaligned_instructions    : 3593378
    dcache hits        : 2147483648
    dcache misses        : 0
    icache hits        : 2147483648
    icache misses        : 0
    instructions        : 2147483648
    
    
    Memory: 4k page, physical 239672k(159532k free), swap 524280k(523696k free)
    
    vm_info: OpenJDK Zero VM (25.102-b02) for linux-mipsel JRE (1.8.0_102-Optware-ng-b02), built on Nov 27 2017 16:25:02 by "jenkins" with gcc 7.2.0
    
    time: Wed Nov 29 23:49:50 2017
    elapsed time: 0 seconds (0d 0h 0m 0s)

**Comment by triceo** [comment]
Díky za report! Co přesně to je za hardware?
Na první pohled to nevypadá jako problém robota, ale pokusím se vymyslet, co s tím.

**Comment by triceo** [comment]
Jo, už to vidím, AsusWRT.

**Comment by triceo** [comment]
@marek-stopka Předně bych asi doporučil zkusit sehnat novější verzi OpenJDK - jestli to čtu správně, máte tam `1.8.0_102`. To je rok a půl stará věc. Dost možná to za tu dobu opravili. Nicméně koukám, že podpora pro MIPS nebyla nikdy oficiální, takže to nevypadá dobře.

**Comment by marek-stopka** [comment]
@triceo, tak to mě mrzí, že MIPS není podporovaný, holt budu muset RoboZonky nahodit na nějaké VPS :) Tak moc abych si ručně kompiloval vlastní Javu na pokus o to, jestli to na ní pojede to zas na tom routeru nepotřebuju, crosskompilace a další věci s tím spojené by vzhledem k tomu, že ani nemám žádný stroj s Linuxem, ale jenom Mac OS X nemusely dopadnout dobře... Holt mi RoboZonky poběží na notebooku, než nahodím nový domácí server s KVMkem.

Každopádně díky za rychlou rakci a skvělou podporu!

**Comment by triceo** [comment]
@marek-stopka Mě to trochu mrzí, protože pointa Javy je, aby prostě byla dostupná všude. Holt asi MIPS nebyl pro Oracle nikdy priorita. :-( ARM funguje, pokud byste doma měl nějaké jiné podobné zařízení.
