### ISSUE TITLE
RoboZonky neposílá notifikace u investic na sekundárním trhu

### ISSUE THREAD

**Issue by marek-stopka** [RoboZonky/robozonky#188]
Dobrý den, po navýšení maximální investovatelné částky začal RoboZonky investovat i na sekundárním trhu, což je v pořádku, avšak poté co provedl investici do [půjčky 121712](https://app.zonky.cz/#/marketplace/detail/121712) mi nepřišla e-mailem žádná notifikace.

**Comment by triceo** [comment]
Zdravím. Díky za informaci - můžu vidět nastavení notifikací? (Ideálně bez hesla. :-))

**Comment by marek-stopka** [comment]
Dobrý den, moje nastavení je následující:

    enabled = true
    to = marekstopka@gmail.com
    from = marekstopka@gmail.com
    smtp.username = marekstopka@gmail.com
    smtp.password = **censored**
    smtp.hostname = smtp.gmail.com
    smtp.port = 465
    smtp.requiresSslOnConnect = true
    investmentMade.enabled = true
    hourlyMaxEmails = -1

**Comment by marek-stopka** [comment]
A tady je screenshot o investicích na sekundárním trhu...
![snimek obrazovky 2017-12-08 v 18 17 53](https://user-images.githubusercontent.com/18139116/33777199-266e7a78-dc44-11e7-811c-bee865bd6e45.png)

**Comment by triceo** [comment]
Chcete-li notifikace o zakoupených participacích, potřebujete povolit `investmentPurchased`. Máte povolené pouze `investmentMade`. Dejte vědět, jestli to pomohlo.

Všechny možnosti jsou vypsané tady:
https://github.com/RoboZonky/robozonky/blob/master/robozonky-notifications/src/test/resources/com/github/robozonky/notifications/email/notifications-enabled.cfg

**Comment by marek-stopka** [comment]
@triceo, už to funguje, děkuji...
