### ISSUE TITLE
NullPointerException v rzBackground-thread

### ISSUE THREAD

**Issue by sutaakar** [RoboZonky/robozonky#190]
Verze RoboZonky 4.1.2
OpenJDK 1.8.0_141

Stacktrace - https://gist.github.com/sutaakar/85ed4f51aa4b97519e14c678ee0c1f4d

Zaznamenano pouze jednou, po restartu vsechno funguje jak ma.

**Comment by triceo** [comment]
Na masteru už je to vyřešené - měl jsem tam `TreeMap` která nebyla synchronizovaná, takže docházelo k chybám při vícevláknovém zpracování.

Díky za report!
