### ISSUE TITLE
Čerstvá instalace RoboZonky 4.2.0 vrací vyjímku

### ISSUE THREAD

**Issue by marek-stopka** [RoboZonky/robozonky#191]
Dobrý den;
čerstvá instalace RoboZonky 4.2.0 vrací vyjímku

10:36:55.845 WARN  c.g.r.a.u.DaemonRuntimeExceptionHandler Caught unexpected exception, continuing operation.
java.lang.IllegalStateException: Portfolio not properly initialized.
        at com.github.robozonky.app.configuration.daemon.DaemonOperation.lambda$run$0(DaemonOperation.java:57)
        at java.util.Optional.orElseThrow(Optional.java:290)
        at com.github.robozonky.app.configuration.daemon.DaemonOperation.run(DaemonOperation.java:57)
        at com.github.robozonky.app.configuration.daemon.Skippable.run(Skippable.java:44)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by triceo** [comment]
Díky za report!

Tahle výjimka říká, že se někde předtím stalo něco, co se stát nemělo, a robot teď nemůže pracovat. Tipnu si, že nebylo dostupné síťové připojení. Restart robota by to měl vyřešit. Pokud ne, bude mě zajímat log.

**Comment by marek-stopka** [comment]
@triceo, konektivitou to určitě nebude, protože mi to běží na virtuálním serveru v Indonésii a kdyby nešla konektivita tak nemám RoboZonky jak spustit, protože mám jen SSH konektivitu :) Log přikládám.
[robozonky.log](https://github.com/RoboZonky/robozonky/files/1584765/robozonky.log)

**Comment by triceo** [comment]
Zajímavé. Na `PaymentStatus` enumu se objevila v Zonky API nová hodnota: `IN_WITHDRAWAL`. Takže s novou verzí _RoboZonky_ to nesouvisí, ale bude to potřeba urychleně opravit.

**Comment by marek-stopka** [comment]
O téhle nové hodnotě mi psala už verze 4.1.2; jen nekončila vyjímkou, jen zmínila, že by se robot mohl chovat nepředvídatelně, všechno však fungovalo jak má...

Teď se zdá, že ani verze 4.1.2 nefunguje :)

**Comment by triceo** [comment]
Je to tak. Verze 4.2.0 je záměrně mnohem méně tolerantní k těmhle problémům. Což by běžně nebyl problém - mám dost investic na to, abych si při vývoji takových změn v API všimnul. Ale evidentně jich potřebuju ještě víc. :-) Toho `IN_WITHDRAWAL` jsem si nevšiml, protože žádnou investici v tomhle stavu nemám. _RoboZonky_ 4.2.1 s opravou je na cestě. 

Na okraj - docela by mě zajímalo, jak vypadá taková investice na webu Zonky. Některé jsou "Na cestě", některé jsou "Na tržišti", nemám nejmenší tušení, co bude tahle.

**Comment by marek-stopka** [comment]
Když pošleš `curl`,  kterým to můžu zkusit vytáhnout tak ti to s radostí spustím :)

**Comment by triceo** [comment]
Přes `curl` to jednoduše nepůjde, vyžaduje to OAuth autentizaci. Jedně se podívat do "Lidé, které jsem podpořil", a najít v sekci "Všechny" jednu jedinou investici, která nemá výrazně jiný status. (A taky se může stát, že v tom seznamu vůbec nebude, protože `IN_WITHDRAWAL` nejspíš znamená, že klient odstoupil od úvěrové smlouvy.)

**Comment by marek-stopka** [comment]
Jediná, která není v pořádku a jde to vidět z GUI je tato...
![snimek obrazovky 2017-12-24 v 12 32 54](https://user-images.githubusercontent.com/18139116/34326164-a853976c-e8a6-11e7-892d-1bb5dc3882cc.png)

**Comment by triceo** [comment]
Zajímavé, "na cestě". Takže tuhle situaci nemají nijak zvlášť pokrytou ani v UI. Díky!

**Comment by marek-stopka** [comment]
Tak jsem ještě našel tady tuto...
![snimek obrazovky 2017-12-24 v 12 39 36](https://user-images.githubusercontent.com/18139116/34326201-90fa4754-e8a7-11e7-9930-a4a20aadf105.png)

**Comment by triceo** [comment]
Bingo. :-) Když si tu půjčku člověk dohledá, dostane "Internal Server Error" od Zonky:
https://app.zonky.cz/#/marketplace/detail/182461/

Inu, jdu jim napsat, že to mají rozbitý.

**Comment by triceo** [comment]
4.2.1 je na cestě na mirrory. Díky za report!
