### ISSUE TITLE
"mvn clean build" fails

### ISSUE THREAD

**Issue by marek-stopka** [RoboZonky/robozonky#196]
Zdravím, snažil jsem se vám ušetřit trošku práci s #178, ale když spustím "mvn clean build" tak skončí s následující chybou:

    [INFO] ANTLR 4: Processing source directory /usr/src/robozonky/robozonky-strategy-natural/src/main/antlr4
    [INFO] Processing grammar: com/github/robozonky/strategy/natural/NaturalLanguageStrategy.g4
    [INFO] ------------------------------------------------------------------------
    [INFO] Reactor Summary:
    [INFO] 
    [INFO] RoboZonky: Easy automated investing with Zonky ..... SUCCESS [  1.911 s]
    [INFO] RoboZonky: Public, stable APIs ..................... SUCCESS [ 25.279 s]
    [INFO] RoboZonky: Code shared between various modules ..... SUCCESS [  5.820 s]
    [INFO] RoboZonky: Marketplace support for Zonky and Zotify  SUCCESS [  1.927 s]
    [INFO] RoboZonky: Utility module in support of testing .... SUCCESS [  8.891 s]
    [INFO] RoboZonky: Investment strategy based on natural language FAILURE [  6.964 s]
    [INFO] RoboZonky: Integration with Zonkoid/Zonkios ........ SKIPPED
    [INFO] RoboZonky: Sends e-mail notifications .............. SKIPPED
    [INFO] RoboZonky: Command-line application ................ SKIPPED
    [INFO] RoboZonky Extension: Parent POM .................... SKIPPED
    [INFO] RoboZonky Installer: Parent POM .................... SKIPPED
    [INFO] RoboZonky Installer: Custom panels ................. SKIPPED
    [INFO] RoboZonky Installer: Distributable ................. SKIPPED
    [INFO] ------------------------------------------------------------------------
    [INFO] BUILD FAILURE
    [INFO] ------------------------------------------------------------------------
    [INFO] Total time: 01:32 min
    [INFO] Finished at: 2017-12-31T18:47:50Z
    [INFO] Final Memory: 30M/181M
    [INFO] ------------------------------------------------------------------------
    [ERROR] Failed to execute goal org.antlr:antlr4-maven-plugin:4.7:antlr4 (antlr) on project robozonky-strategy-natural: Execution antlr of goal org.antlr:antlr4-maven-plugin:4.7:antlr4 failed: An API incompatibility was encountered while executing org.antlr:antlr4-maven-plugin:4.7:antlr4: java.lang.ClassFormatError: Unknown constant tag 0 in class file java/lang/Character$UnicodeBlock
    [ERROR] -----------------------------------------------------
    [ERROR] realm =    plugin>org.antlr:antlr4-maven-plugin:4.7
    [ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
    [ERROR] urls[0] = file:/root/.m2/repository/org/antlr/antlr4-maven-plugin/4.7/antlr4-maven-plugin-4.7.jar
    [ERROR] urls[1] = file:/root/.m2/repository/org/codehaus/plexus/plexus-component-annotations/1.5.5/plexus-component-annotations-1.5.5.jar
    [ERROR] urls[2] = file:/root/.m2/repository/org/sonatype/sisu/sisu-inject-bean/2.3.0/sisu-inject-bean-2.3.0.jar
    [ERROR] urls[3] = file:/root/.m2/repository/org/sonatype/sisu/sisu-guice/3.1.0/sisu-guice-3.1.0-no_aop.jar
    [ERROR] urls[4] = file:/root/.m2/repository/org/sonatype/sisu/sisu-guava/0.9.9/sisu-guava-0.9.9.jar
    [ERROR] urls[5] = file:/root/.m2/repository/org/codehaus/plexus/plexus-compiler-api/2.2/plexus-compiler-api-2.2.jar
    [ERROR] urls[6] = file:/root/.m2/repository/org/codehaus/plexus/plexus-utils/3.0.8/plexus-utils-3.0.8.jar
    [ERROR] urls[7] = file:/root/.m2/repository/org/sonatype/plexus/plexus-build-api/0.0.7/plexus-build-api-0.0.7.jar
    [ERROR] urls[8] = file:/root/.m2/repository/org/antlr/antlr4/4.7/antlr4-4.7.jar
    [ERROR] urls[9] = file:/root/.m2/repository/org/antlr/antlr4-runtime/4.7/antlr4-runtime-4.7.jar
    [ERROR] urls[10] = file:/root/.m2/repository/org/antlr/antlr-runtime/3.5.2/antlr-runtime-3.5.2.jar
    [ERROR] urls[11] = file:/root/.m2/repository/org/antlr/ST4/4.0.8/ST4-4.0.8.jar
    [ERROR] urls[12] = file:/root/.m2/repository/org/abego/treelayout/org.abego.treelayout.core/1.0.3/org.abego.treelayout.core-1.0.3.jar
    [ERROR] urls[13] = file:/root/.m2/repository/org/glassfish/javax.json/1.0.4/javax.json-1.0.4.jar
    [ERROR] urls[14] = file:/root/.m2/repository/com/ibm/icu/icu4j/58.2/icu4j-58.2.jar
    [ERROR] urls[15] = file:/root/.m2/repository/backport-util-concurrent/backport-util-concurrent/3.1/backport-util-concurrent-3.1.jar
    [ERROR] urls[16] = file:/root/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.11/plexus-interpolation-1.11.jar
    [ERROR] urls[17] = file:/root/.m2/repository/junit/junit/3.8.1/junit-3.8.1.jar
    [ERROR] Number of foreign imports: 1
    [ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]
    [ERROR] 
    [ERROR] -----------------------------------------------------
    [ERROR] 
    [ERROR] -> [Help 1]
    [ERROR] 
    [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
    [ERROR] Re-run Maven using the -X switch to enable full debug logging.
    [ERROR] 
    [ERROR] For more information about the errors and possible solutions, please read the following articles:
    [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginContainerException
    [ERROR] 
    [ERROR] After correcting the problems, you can resume the build with the command
    [ERROR]   mvn <goals> -rf :robozonky-strategy-natural
    The command 'mvn clean compile' returned a non-zero code: 1
     
Mám následující Dockerfile:

    Mareks-MacBook-Air:robozonky marekstopka$ cat Dockerfile 
    FROM maven:3-jdk-8
    COPY . /usr/src/robozonky
    WORKDIR /usr/src/robozonky
    
    RUN ["mvn", "-X", "clean", "compile"] 

Log `mvn -X clean compile`zde...
[docker-build.log](https://github.com/RoboZonky/robozonky/files/1595407/docker-build.log)

Zkoušel jsem různé verze Javy i Mavenu a všechny skončili s nějakou chybou; s touto verzi se mi podařilo dostat nejdále... (A pro jistotu jsem to testoval nad master i 4.2.1 branchí)...

**Comment by triceo** [comment]
Zdravím!

Prozkoumal jsem ten log, a hlavní problém bude tohle: `java.lang.ClassFormatError: Unknown constant tag 0 in class file java/lang/Character$UnicodeBlock`. Za dobu, co dělám s Javou, jsem takový problém ještě neviděl. Ve stack trace byly zmínky o ANTLR, tak jsem ho pro jistotu upgradoval (commit 0c3393b), ale nemyslím, že to něco změní.

Trochu jsem googlil, a [tohle](https://stackoverflow.com/questions/12333849/classformaterror-unknown-constant-tag-in-class-xy) by naznačovalo, že se jedná o problém se samotnou Javou. Asi bych doporučil začít s nějakou [standardní OpenJDK image](https://hub.docker.com/_/openjdk/) a zkusit to znovu. Pokud nefungují tyhle oficiální image, tak máme opravdu problém.

Na Windows i na Linuxu se _RoboZonky_ normálně buildí, viz Travis a AppVeyor. Takže je ještě jedna možnost, a to že to nějak souvisí s Macem. Uvidím, jestli se k nějakému Macu dostanu v práci, abych si to vyzkoušel.

Nicméně pozor - `mvn clean compile` nebude fungovat tak jako tak. Selže to v `robozonky-installer-app`, který očekává, že `robozonky-installer-panels` (předchozí modul v build chainu) je v repu. Takže lepší volba bude `mvn clean install -DskipTests`.

**Comment by triceo** [comment]
Ad. Maven - Travis používá 3.3.9, já mám lokálně 3.5.2. Obě fungují.

**Comment by triceo** [comment]
Spustil jsem to u kolegy na Macu, `mvn clean install` prošel do zelena vč. všech testů.

**Comment by triceo** [comment]
Chybu se nepodařilo reprodukovat, zavírám.
