### ISSUE TITLE
Podpora pro pojištění

### ISSUE THREAD

**Issue by triceo** [RoboZonky/robozonky#201]
Zonky zavádí pojištění schopnosti splácet. Už je to v API (fc4977cb8412445852d173fff1fc36fe8e00cf2a). Bude potřeba to přidat do strategie.

**Comment by triceo** [comment]
@jhrcek FYI. Will be doing a final release in about one week's time. But this change is fully backwards compatible, so the web tool need not support it. No rush.

**Comment by jhrcek** [comment]
@triceo ok, let me know if there's any action required from my side.

**Comment by triceo** [comment]
@jhrcek At some point, the extra condition would have to be added to the web tool. I'll leave it up to you, when you can get to it.

**Comment by jhrcek** [comment]
@triceo ok, I missed that change. Will add the new condition it within the next two weeks

**Comment by triceo** [comment]
@jhrcek Yes please.
