### ISSUE TITLE
Dosažitelný výnos v % nedává příliš smysl

### ISSUE THREAD

**Issue by marek-stopka** [RoboZonky/robozonky#203]
Ahoj,
nová verze RoboZonky zavádí v e-mail notifikacích nové pole `Dosažitelný výnos`, při procentuálním vyjádření je uveden přívlastek `p.a.`, avšak poskytnutá hodnota není `p.a.`, ale čistě poměr celkového výnosu vůči celkové výši investice do participace přepočtený na "pokus" o anualizovanou metriku, která vzniká prostým podělením celkového úrokového výnosu vyjádřeného v procentech investované částky předpokládaným počtem měsíců, což není `p.a.` metrika, protože ta se vyjadřuje jen ze zbývající dlužné částky.

Podle mě by dávalo větší smysl, kdyby byly provedeny následující úpravy:
* Vedle `Rating` bude navíc uvedeno `(N% p.a. - M % p.a. - L % p.a. = P % p.a.)` kde N je úroková míra ratingu, M je investorský poplatek pro daný rating, L jsou předpokládané rizikové náklady pro daný rating a P je rozdíl těchto 3 hodnot
* Vedle `Dosažitelný výnos` bude uvedeno `(M %; N %)` kde M je podíl celkového výnosu na celkové investované částce vyjádřený v %; N je pak podíl celkového výnosu vyjádřeného v procentech na období trvání půjčky dlouhé jeden rok; `Dosažený výnos` je tedy metrikou, která nemá rozměr.

**Comment by triceo** [comment]
Zdravím - pro výpočet výnosu používám podle mého názoru korektní finanční funkce, konkrétně:

https://github.com/RoboZonky/robozonky/blob/master/robozonky-common/src/main/java/com/github/robozonky/util/FinancialUtil.java

Které jsou re-implementací následujících do Javy, v Excelu existují taktéž:

https://www.experts-exchange.com/articles/1948/A-Guide-to-the-PMT-FV-IPMT-and-PPMT-Functions.html

Tyto funkce, pokud je správně chápu, berou zbývající dlužnou částku v úvahu a jedná se tedy o skutečně čisté `p. a.` Jen s tím rozdílem, že jsem si dovolil přidat očištění o Zonky poplatek.

**Comment by triceo** [comment]
Po diskusi na Facebooku uznávám chybu. :-)
