### ISSUE TITLE
Neinvestovat, má-li být půjčka obratem prodána

### ISSUE THREAD

**Issue by triceo** [RoboZonky/robozonky#209]
Robot dosud investoval pouze na základě investičních filtrů. Pokud však nějaká takto vzniklá participace odpovídala některému z prodejních filtrů, robot ji zase hned prodal. Nově ji robot vůbec nekoupí.

**Comment by v6ak** [comment]
Možná stojá za zvážení v takovémto případě poslat uživateli nějaký varovný e-mail, protože to zavání chybně napsanou strategií.

Analogická situace může být, pokud by půjčka měla být obratem znovu nakoupena. (Pokud si dobře vzpomínám, v této situaci ji RoboZonky ignoruje už nějaký čas.)

Ještě lepší by bylo to umět detekovat staticky, ale to by asi byla moc práce a hlavně závazek do budoucna.

**Comment by triceo** [comment]
@v6ak Dobrá poznámka. Zamyslím se, co by se s tím dalo udělat.
