### ISSUE TITLE
Notifikace o nárůstu zůstatku nemá dostatečně zřejmý předmět

### ISSUE THREAD

**Issue by triceo** [RoboZonky/robozonky#214]
https://groups.google.com/d/msg/robozonky-users/5cCr23PQB_g/eQ6a8cM0BQAJ

**Comment by marek-stopka** [comment]
Dovolil bych si také navrhnout aby notifikace o nové investici, nebo
zakoupené participaci obsahovala rating, kterého se týká... Takhle musím
zbytečně ty maily otevírat :)

**Comment by triceo** [comment]
To tam není? Zcela jistě to tam bylo. To muselo vypadnout teprve nedávno.

**Comment by triceo** [comment]
Jo aha, moment - v předmětu. Tam to vážně není.
