### ISSUE TITLE
Robot selže při pokusu doinvestovat ručně zainvestovanou půjčku

### ISSUE THREAD

**Issue by samurajj** [RoboZonky/robozonky#217]
Neodchycená výjimka při pokusu o investici 200Kč do půjčky, kde jsem manuálně investoval 400Kč.

RoboZonky 4.3.3, OS: Centos 6

Záznam z logu opakující se každých cca 10s: 

> 17:54:21.941 [rzDaemon-2] INFO  c.g.robozonky.common.remote.Zonky Investing into loan #218034.
> 17:54:22.045 [rzDaemon-2] DEBUG c.g.r.c.remote.AuthenticatedFilter HTTP POST Response from https://api.zonky.cz/marketplace/investment: 400 Bad Request.
> 17:54:22.045 [rzDaemon-2] DEBUG c.g.r.c.remote.AuthenticatedFilter Response body is: {"error":"multipleInvestment","uuid":"5cf785f6-dd94-42b4-92e7-f31e7448ce23"}
> 17:54:22.045 [rzDaemon-2] WARN  c.g.r.a.c.daemon.InvestingDaemon Caught unexpected exception, continuing operation.
> javax.ws.rs.BadRequestException: HTTP 400 Bad Request
> 	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.handleErrorStatus(ClientInvocation.java:214)
> 	at org.jboss.resteasy.client.jaxrs.internal.proxy.extractors.DefaultEntityExtractorFactory$3.extractEntity(DefaultEntityExtractorFactory.java:50)
> 	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:107)
> 	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:76)
> 	at com.sun.proxy.$Proxy37.invest(Unknown Source)
> 	at com.github.robozonky.common.remote.Zonky.lambda$invest$0(Zonky.java:107)
> 	at com.github.robozonky.common.remote.ApiBlueprint.lambda$execute$0(ApiBlueprint.java:28)
> 	at com.github.robozonky.common.remote.Api.execute(Api.java:46)
> 	at com.github.robozonky.common.remote.ApiBlueprint.execute(ApiBlueprint.java:31)
> 	at com.github.robozonky.common.remote.Zonky.invest(Zonky.java:106)
> 	at com.github.robozonky.app.investing.Investor$Builder.lambda$build$1(Investor.java:176)
> 	at com.github.robozonky.app.investing.Investor.investLocallyFailingOnCaptcha(Investor.java:96)
> 	at com.github.robozonky.app.investing.Investor.investOrDelegateOnCaptcha(Investor.java:106)
> 	at com.github.robozonky.app.investing.Investor.invest(Investor.java:91)
> 	at com.github.robozonky.app.investing.Session.invest(Session.java:157)
> 	at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
> 	at java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:373)
> 	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:419)
> 	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
> 	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270)
> 	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
> 	at java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:373)
> 	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
> 	at java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:352)
> 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
> 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
> 	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
> 	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
> 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
> 	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
> 	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270)
> 	at java.util.Iterator.forEachRemaining(Iterator.java:116)
> 	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
> 	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
> 	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270)
> 	at java.util.TreeMap$ValueSpliterator.tryAdvance(TreeMap.java:2921)
> 	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
> 	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
> 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
> 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
> 	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
> 	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
> 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
> 	at java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:449)
> 	at com.github.robozonky.app.investing.Session.invest(Session.java:114)
> 	at com.github.robozonky.app.investing.Session.invest(Session.java:102)
> 	at com.github.robozonky.app.investing.Investing.lambda$execute$1(Investing.java:52)
> 	at com.github.robozonky.common.remote.ApiProvider.authenticated(ApiProvider.java:152)
> 	at com.github.robozonky.app.authentication.TokenBasedAccess.call(TokenBasedAccess.java:49)
> 	at com.github.robozonky.app.investing.Investing.execute(Investing.java:52)
> 	at com.github.robozonky.app.investing.Investing.execute(Investing.java:31)
> 	at com.github.robozonky.app.util.StrategyExecutor.invest(StrategyExecutor.java:59)
> 	at com.github.robozonky.app.util.StrategyExecutor.lambda$apply$1(StrategyExecutor.java:68)
> 	at java.util.Optional.map(Optional.java:215)
> 	at com.github.robozonky.app.util.StrategyExecutor.apply(StrategyExecutor.java:68)
> 	at com.github.robozonky.app.configuration.daemon.InvestingDaemon$InitializingInvestor.lambda$null$0(InvestingDaemon.java:72)
> 	at com.github.robozonky.marketplaces.AbstractMarketplace.lambda$run$0(AbstractMarketplace.java:43)
> 	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:891)
> 	at java.util.concurrent.CopyOnWriteArraySet.forEach(CopyOnWriteArraySet.java:404)
> 	at com.github.robozonky.marketplaces.AbstractMarketplace.run(AbstractMarketplace.java:43)
> 	at com.github.robozonky.app.configuration.daemon.InvestingDaemon$InitializingInvestor.lambda$new$1(InvestingDaemon.java:75)
> 	at com.github.robozonky.app.configuration.daemon.InvestingDaemon$InitializingInvestor.accept(InvestingDaemon.java:81)
> 	at com.github.robozonky.app.configuration.daemon.InvestingDaemon$InitializingInvestor.accept(InvestingDaemon.java:57)
> 	at com.github.robozonky.app.configuration.daemon.DaemonOperation.run(DaemonOperation.java:59)
> 	at com.github.robozonky.app.configuration.daemon.Skippable.run(Skippable.java:43)
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> 	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
> 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
> 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:748)

**Comment by triceo** [comment]
Díky za report!

**Comment by triceo** [comment]
Verze 4.3.4 to řeší.
