### ISSUE TITLE
Robot nenakupuje - chapu strategii spravne?

### ISSUE THREAD

**Issue by emx0r** [RoboZonky/robozonky#230]
Zdravim,

snazim se nastavit robota na trochu agresivnejsi strategii. Chci aby investoval do pujcek pokud je jejich urok vetsi nez 15% a zaroven doba splaceni je kratsi nez 18 mesicu?

Na Zonky vidim ze takovychto pujcek jiz probehlo mnoho, muj robot ovsem zadnou investici neudelal. V logu neni nic co by me privedlo na stopu co muze byt spatne.

Prikladam nastaveni strategie v pripade ze jsem ji spatne pochopil. Diky

- Obecná nastavení
Robot má udržovat progresivní portfolio.
Běžná výše investice je 200 až 1000 Kč.

- Filtrování tržiště
Ignorovat vše, kde: úrok nedosahuje 15,0 % p.a.
Ignorovat vše, kde: délka přesahuje 18 měsíců.

**Comment by marek-stopka** [comment]
Já bych na to šel asi cestou upravení mojí strategie:

```
# Konfigurace strategie vytvořená 23.11.2017 nástrojem natural-strategy-setup verze ef43711
Tato strategie vyžaduje RoboZonky ve verzi 4.1.0 nebo pozdější.
- Obecná nastavení
Robot má udržovat prázdné portfolio.
Běžná výše investice je 200 Kč.
Investovat maximálně 1 % výše úvěru.

- Úprava struktury portfolia
Prostředky v ratingu A** tvoří 3 % aktuální zůstatkové částky.
Prostředky v ratingu A* tvoří 6 % aktuální zůstatkové částky.
Prostředky v ratingu A++ tvoří 9 % aktuální zůstatkové částky.
Prostředky v ratingu A+ tvoří 0 % aktuální zůstatkové částky.
Prostředky v ratingu A tvoří 12 % aktuální zůstatkové částky.
Prostředky v ratingu B tvoří 55 až 75 % aktuální zůstatkové částky.
Prostředky v ratingu C tvoří 13 % aktuální zůstatkové částky.
Prostředky v ratingu D tvoří 2 % aktuální zůstatkové částky.

- Výše investice
Do úvěrů v ratingu A** investovat 200 až 200 Kč.
Do úvěrů v ratingu A* investovat 200 až 200 Kč.
Do úvěrů v ratingu A++ investovat 200 až 200 Kč.
Do úvěrů v ratingu A+ investovat 200 až 200 Kč.
Do úvěrů v ratingu A investovat 200 až 200 Kč.
Do úvěrů v ratingu B investovat 200 až 1200 Kč.
Do úvěrů v ratingu C investovat 200 až 200 Kč.
Do úvěrů v ratingu D investovat 200 až 200 Kč.

- Filtrování tržiště
Ignorovat vše, kde: rating je lepší než A++; délka přesahuje 48 měsíců.
Ignorovat vše, kde: rating je A, A+ nebo A++; délka přesahuje 48 měsíců.

Prodej participací zakázán.
```

Tzn, prázdné portfolio + nastavení ratingů co mají ten výnos nižší než těch 15% na 0%.

**Comment by emx0r** [comment]
diky, vyzkousim

**Comment by emx0r** [comment]
tak ani toto nepomohlo. Zacinam mit pocit ze pro tato kriteria neni robot dostatecne rychly. V logu nejdou tyto pujcky ani videt. Jak casto se robot probouzi a kontroluje trh?

**Comment by triceo** [comment]
Interval kontroly tržiště je každých 10 vteřin. Ale jsou výjimky:

Nemáte-li nic v peněžence, nebude se nic kontrolovat. Informace o zůstatku se aktualizuje každých 5 minut. Pokud se na tržišti nic nezměnilo od doby, kdy bylo naposledy zkontrolováno (tj. nepřibyla žádná nová půjčka), robot taky nebude nic dělat. Změna zůstatku v každém případě způsobí novou kontrolu tržiště.

Z výše uvedeného vyplývá, že existuje malá teoretická šance, že nějaká půjčka tímhle sítem proklouzne. Stejně tak existuje šance, že nějaká půjčka na tržišti nevydrží ani těch 10 vteřin - ale to se také stává jen velmi zřídka. Je pravda, že v situaci "jenom D jenom do 18 měsíců" jste téhle možnosti vystaven asi nejvíc, co to vůbec jde, ale zároveň je to také velmi neobvyklý způsob používání robota.

**Comment by emx0r** [comment]
diky za vysvetleni

**Comment by triceo** [comment]
Z diskuse vyplývá, že nejde o bug. I tak děkuji za report!
