### ISSUE TITLE
podpora pro znak "+" v emailove adrese 

### ISSUE THREAD

**Issue by vvvlc** [RoboZonky/robozonky#241]
Ahoj,
Zonky login umoznuje znak + v emailove adrese napr. abc+def@gmail.com.
Gmail + taky podporuje a abc+def@gmail.com je posle uzivateli abc@gmail.com.
Bohuzel validace emailu v installatoru je priliz striktni.

![2018-05-04-971](https://user-images.githubusercontent.com/15854496/39614165-f55f7854-4f6d-11e8-9116-68c48c204621.jpg)

**Comment by triceo** [comment]
Díky za report! Opravím.
