### ISSUE TITLE
robozonky docker image robozonky/robozonky:latest contains robozonky-api-4.6.3.jar

### ISSUE THREAD

**Issue by vvvlc** [RoboZonky/robozonky#260]
Hi 
latest docker image contains older version of robozonky 4.6.3 not latest 4.6.4.
Regards
Vitek

**Comment by triceo** [comment]
`robozonky:latest`  is back to latest again. I don't know what happened, Dockerhub nor Github give me any logging. If it happens again, I'll dig deeper - for now, I triggered the Docker build manually.

Thanks for reporting!
