### ISSUE TITLE
SMTP server bez autentizace

### ISSUE THREAD

**Issue by msantavy** [RoboZonky/robozonky#261]
Poslední dobou se snažím o rozjetí email notifikací, protože jsem zjistil, že mají docela zajímavé informace. Leč neúspěšně. 

Uspěl jsem až dnes, a je to tím, že se nechci a nemůžu autentizovat na SMTP server.

Prosím tedy o kontrolu, že když není zadán smtp.username a smtp.password, nebude se autentizovat.

Pokud tedy v AbstractEmailingListener.createNewEmail v 4.6, resp. EmailHandler v master, nezavolám email.setAuthentication(getSmtpUsername(), getSmtpPassword()), krásně mi začnou chodit maily.

Díky,
Mirek

**Comment by triceo** [comment]
Díky, podívám se na to.

**Comment by msantavy** [comment]
Díky moc,
Mirek
