### ISSUE TITLE
Integrace se Stonky

### ISSUE THREAD

**Issue by triceo** [RoboZonky/robozonky#274]
Stonky je Google Sheets add-on který generuje super statistiky o portfoliu. RoboZonky by se s ním měl naučit integrovat.

**Comment by vvvlc** [comment]
Ahoj,
Mas nejakou predstavu jak by ta integrace mela vypadat? 
Ja bych to videl takto:

1. jako uzivatel si udelam privatni kopii Stonky spreadsheetu
1. do Robozonky konfigurace pridam lokaci toho spreadsheetu na googledrive
1. robozonky by mel na importovat ty dva xls soubory ze zonky do toho spreadsheetu
1. idealne spustit tu analyzu dat :-) ale to by asi potrebovalo fantomjs.

**Comment by triceo** [comment]
@vvvlc 
- 1-3 už je hotový. :-) Dokonce to ten spreadsheet klonuje samo a aktualizuje na novou verzi.
- Problém je 4. 
- A druhý problém je, že až bude ze Stonky oficiální Google add-on, dost možná nebudu moct dělat vůbec nic z toho.

Ve výsledku se zatím přikláním k tomu, že počkám, že bude Stonky oficiální, a pak udělám, co půjde udělat. Nechci lidem dneska dodat nějakou feature, abych jim zítra 90 % té feature zase vzal.
