### ISSUE TITLE
Emailová notifikace o zesplatnění obsahuje špatné údaje

### ISSUE THREAD

**Issue by msantavy** [RoboZonky/robozonky#281]
Špatně je spočítáno počet zbývajících splátek, chybí informace o tom, kolik jich bylo zaplaceno, anebo kdy byla půjčka investována (např údaj Doba držení při splacení půjčky)

Například následující splátka byla zafinancována dne 29.6.2017. Tohle je text notifikačního mailu:
Půjčka č. 100891 (B, 84 m.) byla zesplatněna
Půjčka č. 100891 Auto byla zesplatněna.
Zbývá splátek:	1 z 84
Zbývající jistina:	1 809,35 Kč z 2 000 Kč
Parametry půjčky
Rating:	B 
Výše úvěru:	75 000 Kč
Délka splácení:	84 měsíců
Účel:	Auto-moto
Klient:	Zaměstnanec, Zlínský kraj
Pojištěno:	Ne.

Možná to vrací špatně Zonky, v Excelu jsou také podobná čísla. Možná je to dobře, protože má přijít jen jedna velká splátka, ale pak mi to ale nic neříká. 

Ideálně by bylo pěkné vidět - jak dlouho půjčku držím, jak dlouho je v prodlení (anebo počet zaplacených splátek).

Dalo by se s tím něco udělat?

**Comment by triceo** [comment]
Tohle je problém. :-( U zesplatněných *nikde* v systému není napsáno, kdy jste je zainvestoval. Dokonce tam není ani napsáno, kdy byla zesplatněna. Ta jednička taky jde přímo ze Zonky. Nicméně souhlasím, že to není ideální - chtělo by to, aby se s tím robot dokázal vypořádat nějak lépe.

**Comment by msantavy** [comment]
Zonky export do Excelu to odněkud zjistí - datum zafinancování částky uvede
správně. To se samozřejmě může lišit od data, kdy jsem financoval já, ale
prakticky jen v případě, že jsem participaci koupil na sekundárním trhu.
Nedalo by se z tohoto vyjít? Proč vlastně Zonky dává po zesplatnění ty
podivné čísla? Zkusím to zjistit.



st 18. 7. 2018 v 16:29 odesílatel Lukáš Petrovický <notifications@github.com>
napsal:

**Comment by msantavy** [comment]
Ještě jednu věc jsem zapomněl - bylo by pěkné tam mít uvedeny informace z
vymáhaní, podobně jako u půjček v prodlení...



st 18. 7. 2018 v 16:36 odesílatel Miroslav Šantavý <msantavy@post.cz>
napsal:

**Comment by msantavy** [comment]
Posílám diskuzi na Zonky chatu o významu toho čísla. Mně to tedy pořad není jasné, a asi šli ze Zonky už domů. Pokud Vy to z toho pochopíte, super.

**Comment by msantavy** [comment]
Dobrý den, dnes se mi zesplatnila další půjčka - zonky128381. Vždy mě zarazilo, že zmizel údaj, kolik zbývá splátek a místo něj naskočilo jiné, malé, číslo. Co to číslo znamená?
V tomto případě tedy 1 z 84. V jiném případě např 5 ze 33.
--------------------
Karolína avatar
Dobrý den, Miroslave, 
to dělá to zesplatnění. To, že zmizí počet půjček z 84 na 1, může být i odstoupení od smlouvy, znamená to, že klient nemá nadále splátkový kalendář, ale částku vrátí jednorázově v případě 5 z 33, se jedná o počet proběhlých splátek vůči celkovému počtu splátek, které měl klient původně uhradit.
Karolína
--------------------
Tomu nerozumím. Takže když je to 1 z 84, tak to v budoucnu vrátí jednorázově, když je psáno 5 z 33 nebo 2 z 19 tak v minulost zaplatil 5 nebo 2 splátky?
--------------------
Karolína avatar
Pokud je to např. 5 z 33, tak klient uhradil v minulosti 4 splátky a ta 5. tedy bude poslední a bude to celá zbývající jistina. V případě 1 z 84, k žádné splátce nedošlo a bude tedy jen jedna "splátka", která představuje celou jistinu + úrok za dny, kdy byla půjčka aktivní.
--------------------
Takže to číslo udává počet splátek před zesplatněním, plus tu jednu poslední velkou splátku kvůli zesplatnění?
Tj. klient zaplatil 4 splátky, pak se půjčka zesplatnila, a poté má zaplatit pátou poslední?
--------------------
Karolína avatar
Ano, v podstatě to tak je, akorát to není klasická splátka ale celá zbývající jistina.
--------------------
Jasně, zbývající část.
Ale myslím, že to tak není.
--------------------
Karolína avatar
A jak myslíte že to je? :)
--------------------
Právě u té dnes zesplatněné, kde je 1 z 84 nějaké splátky v minulosti rozhodně proběhly, u "Vrátilo se mi" mám uvedeno 190,65 Kč.
Podle toho, co jsme si řekli, by tam žádné splátky v minulosti být neměly, měla by tam být nula.
Podle exportu do Excelu proběhlo 13 splátek.
--------------------
Karolína avatar
Nemáte snímek obrazovky? 
--------------------
Můžu udělat. Jaké obrazovky,
?
--------------------
Karolína avatar
Kde máte ta čísla, která nám nesedí :) 
--------------------

A ještě transakce této půjčky v Excelu:

--------------------
Karolína avatar
Už rozumím za čísla udávají, že zbývá 1 z 84 splátek (celá částka zesplatněna). 
--------------------

Já pořád ne :). Co tedy znamená o řádek níž 7 z 84?
Před 26 min.. Zatím není viditelné

**Comment by triceo** [comment]
@msantavy Viděl to takhle:

- Zbývající počet splátek z notifikace zmizí úplně. Soudě podle konverzace výše, to číslo je jednak k ničemu, druhak aktivně matoucí.
- Místo toho přibyde datum zainvestování - tj. buď první investice, nebo nákupu na sekundáru.
- Přidám informace o vymáhání.

Co Vy na to?

**Comment by msantavy** [comment]
Souhlasím, jen to číslo ještě řeším. 

Vypadá to, že v případě, že je tam 1, znamená to, že zesplatnění vyšlo ze strany klienta, který odstoupil od smlouvy. Což by pak nebylo snad negativní, a snad by pak půjčka ani nemusela být vedena jako problematická. Ještě si to potvrzuju a dojasňuju na chatu. Je to těžké. Řeší se to různě s kolegyněma. Včera jsem bohužel neměl moc času se tomu věnovat.

**Comment by msantavy** [comment]
Stále řeším. Osobně si začínám myslet, že to je součet jedné poslední velké splátky zbývající jistiny a počtu předem neuhrazených splátek. Jenže mi to zatím nikdo takto nepotvrdil.

**Comment by msantavy** [comment]
Jo, jenže takhle to neřekli, a uvádějí příklady, které neodpovídají skutečnostem. Jako např. posledně zmiňovali, že to může znamenat, když klient během 30 dnů požádá o zrušení půjčky. 

Pak bych snad ale řekl, že se ani nejedná ani o problematickou půjčku, ani o zesplatnění. Ale záleží od definice...

**Comment by msantavy** [comment]
Tak jsme se dobrali k závěru. Číslo je součet jedné poslední velké splátky zbývající jistiny (zesplatněné) a počtu dříve (před zesplatněním) neuhrazených splátek. Případný splátkový kalendář v rámci insolvence není a nebude v tomto čísle zohledněn.

Číslo tedy jaksi něco smysluplného udává, otázka jak to chápou ostatní. Zonky říkali, že zapracují na zpřehlednění, ale znáte je.

Za mě bych to číslo v reportu nechal a přidal:
- datum zainvestování - tj. buď první investice, nebo nákupu na sekundáru
- informace o vymáhání

Co myslíte?

**Comment by msantavy** [comment]
Číslo vlastně říká, s kolika splátkami je klient v prodlení. Např. 4 z 84 říká, že 3 splátky chybí. 1 z 84 říká pravděpodobně, že dlužník sám vyhlásil insolvenci a Zonky půjčku zesplatnilo. Ale neměla by chybět žádná splátka.
