### ISSUE TITLE
Notice about unexpected API change

### ISSUE THREAD

**Issue by adambisek** [RoboZonky/robozonky#289]
Since today (but I had Robozonky for few consecutive days shutted down) I am experiencing belowed notice on startup. Just reporting, I can't assess severity of this error :)

```c.g.r.api.remote.entities.Statistics Trying to set value '[{day=2018-08-10T00:00:00.000+02:00, principalAmount=46.62, interestAmount=7.42, penaltyAmount=0.0}, {day=2018-08-11T00:00:00.000+02:00, principalAmount=15.01, interestAmount=4.03, penaltyAmount=0.0}, {day=2018-08-12T00:00:00.000+02:00, principalAmount=221.82, interestAmount=33.5, penaltyAmount=0.0}, {day=2018-08-13T00:00:00.000+02:00, principalAmount=49.67, interestAmount=9.51, penaltyAmount=0.0}, {day=2018-08-14T00:00:00.000+02:00, principalAmount=59.79, interestAmount=14.04, penaltyAmount=0.0}, {day=2018-08-15T00:00:00.000+02:00, principalAmount=658.04, interestAmount=105.36, penaltyAmount=0.0}, {day=2018-08-16T00:00:00.000+02:00, principalAmount=707.97, interestAmount=111.05, penaltyAmount=0.0}, {day=2018-08-17T00:00:00.000+02:00, principalAmount=255.4, interestAmount=49.48, penaltyAmount=0.0}, {day=2018-08-18T00:00:00.000+02:00, principalAmount=426.31, interestAmount=85.44, penaltyAmount=0.0}, {day=2018-08-19T00:00:00.000+02:00, principalAmount=217.18, interestAmount=45.66, penaltyAmount=0.0}, {day=2018-08-20T00:00:00.000+02:00, principalAmount=901.47, interestAmount=158.45, penaltyAmount=0.0}, {day=2018-08-21T00:00:00.000+02:00, principalAmount=119.47, interestAmount=13.15, penaltyAmount=0.0}, {day=2018-08-22T00:00:00.000+02:00, principalAmount=109.19, interestAmount=12.81, penaltyAmount=0.0}, {day=2018-08-23T00:00:00.000+02:00, principalAmount=70.76, interestAmount=10.4, penaltyAmount=0.0}, {day=2018-08-24T00:00:00.000+02:00, principalAmount=7.96, interestAmount=10.3, penaltyAmount=0.0}, {day=2018-08-25T00:00:00.000+02:00, principalAmount=202.09, interestAmount=55.83, penaltyAmount=0.0}, {day=2018-09-01T00:00:00.000+02:00, principalAmount=16.71, interestAmount=6.87, penaltyAmount=0.0}, {day=2018-09-05T00:00:00.000+02:00, principalAmount=48.01, interestAmount=14.49, penaltyAmount=0.0}, {day=2018-09-06T00:00:00.000+02:00, principalAmount=41.63, interestAmount=6.68, penaltyAmount=0.0}, {day=2018-09-07T00:00:00.000+02:00, principalAmount=26.11, interestAmount=9.07, penaltyAmount=0.0}]' to an unknown property 'expectedPayments'. Indicates an unexpected API change.```

**Comment by triceo** [comment]
@adambisek This is already fixed on master, and therefore in future 4.8.0. If I ever do another 4.7.x release, it'll be fixed there too. (See b36455eed68d0cb8b3acd76f971952730d7ade6e.) But rest assured it is harmless, it has no impact on anything.

Thanks for reporting anyway!

**Comment by adambisek** [comment]
Great! Thanks for quick response!
