### ISSUE TITLE
Support for "prefer insured loans" option

### ISSUE THREAD

**Issue by marek-stopka** [RoboZonky/robozonky#303]
RoboZonky should have "prefer insured loans" option, if set to true, when set to True, RoboZonky should invest in insured loans first if two loans matching the other investment criteria (such as length and rating) are available.

**Comment by triceo** [comment]
This is actually the default (and only) behavior. :-)

**Comment by triceo** [comment]
See https://github.com/RoboZonky/robozonky/blob/master/robozonky-strategy-natural/src/main/java/com/github/robozonky/strategy/natural/PrimaryMarketplaceComparator.java#L33
