### ISSUE TITLE
Setting SMTP notification to seznam

### ISSUE THREAD

**Issue by ondrejFuchs** [RoboZonky/robozonky#304]
I can not set email notifications for the Email account "Seznam". The settings are: smtp.seznam.cz, 465, Requires authentication (Yes), Smtp account and password filled in (Yes), Requires TLS (Yes), Requires SSL (Yes). The email is not the same as the Zonky account.
LOGY:
21: 23: 44.323 ERROR c.g.r.i.EmailSettingsValidator Uncaught exception.

What am I doing wrong?

**Comment by triceo** [comment]
Honestly? I don't know. I've seen Seznam work for some people, and fail for others. Google works reliably for everyone.

**Comment by triceo** [comment]
![snimek z 2018-09-02 19-58-12](https://user-images.githubusercontent.com/247403/44959159-b9f19e00-aeea-11e8-8e47-05b4af1595a9.png)

@ondrejFuchs I used these settings in the installer and the testing e-mail was sent. Can you please review and let me know what you did differently? (I tried experimenting with the SSL/TLS checkboxes and it works as well when both are checked.)

**Comment by triceo** [comment]
OK. It is possible that something I did recently actualy fixed the problem - I'll close this issue now and feel free to reopen when 4.8.0 is out later this week.

Thanks for reporting!
