### ISSUE TITLE
Stonky 0.8 

### ISSUE THREAD

**Issue by vlcvi01** [RoboZonky/robozonky#329]
Stonky 0.8 nove kontroluje jmeno spredsheetu, ve kterem se spusti analyza, aby se zabranilo lidem nahravat data do sdileneho Stonky. Pokud se jmeno souboru nezmenilo, tak vyskoci popup, ktery rika udelej si svoji kopii a analyza se nerozbehne.

Robozonky by asi mel zmenit jmeno Stonky spreadsheetu.

**Comment by triceo** [comment]
To jsou radosti. Podívám se na to.
Díky za report, @vlcvi01 !

**Comment by triceo** [comment]
Bude opraveno v RoboZonky 4.9.0, který vyjde příští víkend. Nebo můžete vyzkoušet už teď v testovací verzi 4.9.0.CR1.
