### ISSUE TITLE
Kratší interval kontroly tržiště

### ISSUE THREAD

**Issue by triceo** [RoboZonky/robozonky#335]
Díky nedávným změnám (#332, #334 a další) je nově robot výrazně rychlejší. V důsledku těchto změn, a vzhledem k aktuální situaci na tržišti, je potřeba snížit interval kontroly obou tržišť z 10 vteřin na 5 vteřin.

**Comment by shakewell9** [comment]
Zdravim, rozumim tomu dobre ze kratsi interval bude ve verzi 5? Nebo si muzu tento parametr upravit uz v soucasne verzi?
Mj. posledni pujcky co jsem koukal 20tis pod 1 rok byly zainvestovane za 2-3 s. (s tim ze tam trdy byla 10 tis od jednoho investora)

**Comment by triceo** [comment]
@shakewell9 Parametr příkazové řádky `-w X` (resp. `-ws X` pro sekundár) nastaví interval kontroly na `X` vteřin. Myslím, že cokoliv pod 5 nebude ve verzi 4.x fungovat příliš dobře, ale dá se to vyzkoušet.

**Comment by shakewell9** [comment]
Díky za rychlou odpověď. Chodí mi to bez problému ve verzi 4.9 na 4 s - kratší jsem nezkoušel, protože zatím robot zvládá investovat do všeho co má.
