### ISSUE TITLE
Test nastavení integrace Stonky

### ISSUE THREAD

**Issue by MartinCerny-awin** [RoboZonky/robozonky#338]
Snažím se zprovoznit integraci se Stonky, ale bohužel se mi to nedaří.

Pro jednodušší odladění by bylo užitečné otestovat nastavení při spuštění robota, tak ja se to v současné době děla u StrategyProvider. Robot by vypsal, že integrace je spravně nastavena (či že integrace chybí) a za jak dlouho (v kolik hodin) proběhně aktualizace dat. Při spuštění by případně mohlo dojít i k prvotní aktualizaci dat.

**Comment by triceo** [comment]
Zdravím. Díky za nápad - je pravda, že robot nijak neindikuje, jestli je ta integrace aktivní. Ono to v tuhle chvíli ani moc nejde, ale uvidím, jestli mě něco napadne.
