### ISSUE TITLE
RoboZonky should increase investment size if new money becomes available in wallet

### ISSUE THREAD

**Issue by mark-stopka** [RoboZonky/robozonky#354]
Currently, if user has ranges defined as investment sizes for certain ratings e.q. 200 - 600 Kč, but only 250 Kč in his wallet, RZ will invest 200 Kč into this new investment, but later, while the loan is still on the marketplace, new money can arrive into wallet. This happens not only at midnight payment processing, but sometimes during the day.

In such case RoboZonky should primarily increase size of the investment in already open investments to the relevant limit; before starting investing in new loans on the marketplace.

**Comment by triceo** [comment]
We no longer have access to the wallet. Closing.
