### ISSUE TITLE
Broken robozonky after latest Zonky API update

### ISSUE THREAD

**Issue by adambisek** [RoboZonky/robozonky#386]
Yesterday I received few notices about unexpected API changes (dont have them, sorry).
Zonky have announced some API changes yesterday, so it makes sense.
But everything was working.

But since today experiencing belowed errors and Robozonky (v5.0.0) is not investing:

STDOUT:
`
0|roboz    | 	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:965) ~[jackson-databind-2.9.5.jar:2.9.5]
0|roboz    | 	at org.jboss.resteasy.plugins.providers.jackson.ResteasyJackson2Provider.readFrom(ResteasyJackson2Provider.java:135) ~[resteasy-jackson2-provider-3.6.2.Final.jar:3.6.2.Final]
0|roboz    | 	at org.jboss.resteasy.core.interception.AbstractReaderInterceptorContext.readFrom(AbstractReaderInterceptorContext.java:66) ~[resteasy-jaxrs-3.6.2.Final.jar:3.6.2.Final]
0|roboz    | 	at org.jboss.resteasy.core.interception.AbstractReaderInterceptorContext.proceed(AbstractReaderInterceptorContext.java:56) ~[resteasy-jaxrs-3.6.2.Final.jar:3.6.2.Final]
0|roboz    | 	at org.jboss.resteasy.client.jaxrs.internal.ClientResponse.readFrom(ClientResponse.java:334) ~[resteasy-client-3.6.2.Final.jar:3.6.2.Final]
0|roboz    | 	... 33 common frames omitted
0|roboz    | Caused by: java.lang.NumberFormatException: For input string: ""
0|roboz    | 	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[na:1.8.0_101]
0|roboz    | 	at java.lang.Integer.parseInt(Integer.java:592) ~[na:1.8.0_101]
0|roboz    | 	at java.lang.Integer.parseInt(Integer.java:615) ~[na:1.8.0_101]
0|roboz    | 	at com.github.robozonky.api.remote.enums.Region$RegionDeserializer.deserialize(Region.java:58) ~[robozonky-api-5.0.0.jar:5.0.0]
0|roboz    | 	at com.github.robozonky.api.remote.enums.Region$RegionDeserializer.deserialize(Region.java:52) ~[robozonky-api-5.0.0.jar:5.0.0]
0|roboz    | 	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:136) ~[jackson-databind-2.9.5.jar:2.9.5]
0|roboz    | 	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288) ~[jackson-databind-2.9.5.jar:2.9.5]
0|roboz    | 	... 43 common frames omitted

0|roboz    | 12:02:54.398 WARN  c.g.r.a.daemon.DaemonInvestmentMode Caught unexpected exception, continuing operation.
0|roboz    | javax.ws.rs.client.ResponseProcessingException: javax.ws.rs.ProcessingException: com.fasterxml.jackson.databind.JsonMappingException: For input string: "" (through reference chain: java.util.ArrayList[21]->com.github.robozonky.api.remote.entities.RawLoan["region"])
0|roboz    | 	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.extractResult(ClientInvocation.java:156) ~[resteasy-client-3.6.2.Final.jar:3.6.2.Final]
0|roboz    | 	at org.jboss.resteasy.client.jaxrs.internal.proxy.extractors.BodyEntityExtractor.extractEntity(BodyEntityExtractor.java:60) ~[resteasy-client-3.6.2.Final.jar:3.6.2.Final]
0|roboz    | 	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invokeSync(ClientInvoker.java:150) ~[resteasy-client-3.6.2.Final.jar:3.6.2.Final]
0|roboz    | 	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:112) ~[resteasy-client-3.6.2.Final.jar:3.6.2.Final]
0|roboz    | 	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:76) ~[resteasy-client-3.6.2.Final.jar:3.6.2.Final]
0|roboz    | 	at com.sun.proxy.$Proxy40.items(Unknown Source) ~[na:na]
0|roboz    | 	at com.github.robozonky.common.remote.Api.lambda$call$0(Api.java:38) ~[robozonky-common-5.0.0.jar:5.0.0]
0|roboz    | 	at com.github.robozonky.common.remote.BlockingOperation.block(BlockingOperation.java:45) ~[robozonky-common-5.0.0.jar:5.0.0]
0|roboz    | 	at java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3323) ~[na:1.8.0_101]
0|roboz    | 	at com.github.robozonky.common.remote.Api.call(Api.java:40) ~[robozonky-common-5.0.0.jar:5.0.0]
0|roboz    | 	at com.github.robozonky.common.remote.PaginatedApi.execute(PaginatedApi.java:66) ~[robozonky-common-5.0.0.jar:5.0.0]
0|roboz    | 	at com.github.robozonky.common.remote.PaginatedApi.execute(PaginatedApi.java:61) ~[robozonky-common-5.0.0.jar:5.0.0]
0|roboz    | 	at com.github.robozonky.common.remote.PaginatedApi.execute(PaginatedApi.java:79) ~[robozonky-common-5.0.0.jar:5.0.0]
0|roboz    | 	at com.github.robozonky.common.remote.PaginatedApi.execute(PaginatedApi.java:71) ~[robozonky-common-5.0.0.jar:5.0.0]
0|roboz    | 	at com.github.robozonky.common.remote.EntityCollectionPageSource.fetch(EntityCollectionPageSource.java:49) ~[robozonky-common-5.0.0.jar:5.0.0]
0|roboz    | 	at com.github.rutledgepaulv.pagingstreams.PagingStreams$SpliteratorBuilder.build(PagingStreams.java:88) ~[paging-streams-0.8.jar:na]
0|roboz    | 	at java.util.stream.AbstractPipeline.sourceSpliterator(AbstractPipeline.java:402) ~[na:1.8.0_101]
0|roboz    | 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:1.8.0_101]
0|roboz    | 	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[na:1.8.0_101]
0|roboz    | 	at com.github.robozonky.app.daemon.InvestingDaemon.execute(InvestingDaemon.java:71) ~[robozonky-app-5.0.0.jar:5.0.0]
0|roboz    | 	at com.github.robozonky.app.daemon.DaemonOperation.lambda$run$0(DaemonOperation.java:55) [robozonky-app-5.0.0.jar:5.0.0]
0|roboz    | 	at com.github.robozonky.app.daemon.DaemonInvestmentMode.runSafe(DaemonInvestmentMode.java:66) ~[robozonky-app-5.0.0.jar:5.0.0]
0|roboz    | 	at com.github.robozonky.app.daemon.DaemonOperation.run(DaemonOperation.java:52) [robozonky-app-5.0.0.jar:5.0.0]
0|roboz    | 	at com.github.robozonky.app.daemon.Skippable.run(Skippable.java:43) [robozonky-app-5.0.0.jar:5.0.0]
0|roboz    | 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_101]
0|roboz    | 	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_101]
0|roboz    | 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_101]
0|roboz    | 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_101]
0|roboz    | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_101]
0|roboz    | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_101]
0|roboz    | 	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_101]
0|roboz    | Caused by: javax.ws.rs.ProcessingException: com.fasterxml.jackson.databind.JsonMappingException: For input string: "" (through reference chain: java.util.ArrayList[21]->com.github.robozonky.api.remote.entities.RawLoan["region"])
0|roboz    | 	at org.jboss.resteasy.client.jaxrs.internal.ClientResponse.readFrom(ClientResponse.java:368) ~[resteasy-client-3.6.2.Final.jar:3.6.2.Final]
0|roboz    | 	at org.jboss.resteasy.client.jaxrs.internal.ClientResponse.readEntity(ClientResponse.java:261) ~[resteasy-client-3.6.2.Final.jar:3.6.2.Final]
0|roboz    | 	at org.jboss.resteasy.specimpl.BuiltResponse.readEntity(BuiltResponse.java:231) ~[resteasy-jaxrs-3.6.2.Final.jar:3.6.2.Final]
0|roboz    | 	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.extractResult(ClientInvocation.java:120) ~[resteasy-client-3.6.2.Final.jar:3.6.2.Final]
0|roboz    | 	... 30 common frames omitted
0|roboz    | Caused by: com.fasterxml.jackson.databind.JsonMappingException: For input string: "" (through reference chain: java.util.ArrayList[21]->com.github.robozonky.api.remote.entities.RawLoan["region"])
0|roboz    | 	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:391) ~[jackson-databind-2.9.5.jar:2.9.5]
0|roboz    | 	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:351) ~[jackson-databind-2.9.5.jar:2.9.5]
0|roboz    | 	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.wrapAndThrow(BeanDeserializerBase.java:1704) ~[jackson-databind-2.9.5.jar:2.9.5]
0|roboz    | 	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:290) ~[jackson-databind-2.9.5.jar:2.9.5]
0|roboz    | 	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151) ~[jackson-databind-2.9.5.jar:2.9.5]
0|roboz    | 	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:286) ~[jackson-databind-2.9.5.jar:2.9.5]
0|roboz    | 	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245) ~[jackson-databind-2.9.5.jar:2.9.5]
0|roboz    | 	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27) ~[jackson-databind-2.9.5.jar:2.9.5]
0|roboz    | 	at com.fasterxml.jackson.databind.ObjectReader._bind(ObjectReader.java:1574) ~[jackson-databind-2.9.5.jar:2.9.5]
0|roboz    | 	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:965) ~[jackson-databind-2.9.5.jar:2.9.5]
0|roboz    | 	at org.jboss.resteasy.plugins.providers.jackson.ResteasyJackson2Provider.readFrom(ResteasyJackson2Provider.java:135) ~[resteasy-jackson2-provider-3.6.2.Final.jar:3.6.2.Final]
0|roboz    | 	at org.jboss.resteasy.core.interception.AbstractReaderInterceptorContext.readFrom(AbstractReaderInterceptorContext.java:66) ~[resteasy-jaxrs-3.6.2.Final.jar:3.6.2.Final]
0|roboz    | 	at org.jboss.resteasy.core.interception.AbstractReaderInterceptorContext.proceed(AbstractReaderInterceptorContext.java:56) ~[resteasy-jaxrs-3.6.2.Final.jar:3.6.2.Final]
0|roboz    | 	at org.jboss.resteasy.client.jaxrs.internal.ClientResponse.readFrom(ClientResponse.java:334) ~[resteasy-client-3.6.2.Final.jar:3.6.2.Final]
0|roboz    | 	... 33 common frames omitted
`

STDERR:
`
0|roboz    | 	at org.apache.commons.lang3.builder.ReflectionToStringBuilder.appendFieldsIn(ReflectionToStringBuilder.java:642)
0|roboz    | 	at org.apache.commons.lang3.builder.ReflectionToStringBuilder.toString(ReflectionToStringBuilder.java:832)
0|roboz    | 	at com.github.robozonky.internal.util.ToStringBuilder.toString(ToStringBuilder.java:45)
0|roboz    | 	at com.github.robozonky.internal.util.ToStringBuilder.createFor(ToStringBuilder.java:40)
0|roboz    | 	at com.github.robozonky.api.remote.entities.sanitized.AbstractMutableLoanImpl.lambda$new$0(AbstractMutableLoanImpl.java:59)
0|roboz    | 	at com.github.robozonky.api.remote.entities.sanitized.AbstractMutableLoanImpl$$Lambda$295/1610245553.get(Unknown Source)
0|roboz    | 	at io.vavr.Lazy.computeValue(Lazy.java:162)
0|roboz    | 	at io.vavr.Lazy.get(Lazy.java:156)
0|roboz    | 	at com.github.robozonky.api.remote.entities.sanitized.AbstractMutableLoanImpl.toString(AbstractMutableLoanImpl.java:409)
0|roboz    | 	at org.slf4j.helpers.MessageFormatter.safeObjectAppend(MessageFormatter.java:299)
0|roboz    | 	at org.slf4j.helpers.MessageFormatter.deeplyAppendParameter(MessageFormatter.java:271)
0|roboz    | 	at org.slf4j.helpers.MessageFormatter.arrayFormat(MessageFormatter.java:233)
0|roboz    | 	at org.slf4j.helpers.MessageFormatter.arrayFormat(MessageFormatter.java:173)
0|roboz    | 	at ch.qos.logback.classic.spi.LoggingEvent.getFormattedMessage(LoggingEvent.java:293)
0|roboz    | 	at ch.qos.logback.classic.spi.LoggingEvent.prepareForDeferredProcessing(LoggingEvent.java:206)
`

Could you help me please Lukas?

**Comment by triceo** [comment]
Hey there!

You are correct - RoboZonky was broken. Thankfully, we've already fixed it yesteday with RoboZonky 5.0.1, see more here:
https://groups.google.com/d/msg/robozonky-users/QzcPfP9u2iU/RMHx9bsPFgAJ

Thanks for reporting!

**Comment by adambisek** [comment]
Thank you! It helped, but the console is being flooded by these messages:

`
0|roboz    | 12:48:16.599 INFO  c.g.r.app.RoboZonkyStartupNotifier ===== RoboZonky 'Unnamed' v5.0.1 at your service! =====
0|roboz    | 12:48:17.724 INFO  c.g.r.api.remote.entities.RawLoan Trying to set value '0.1499' to an unknown property 'revenueRate'. Indicates an unexpected API change.
0|roboz    | 12:48:17.724 INFO  c.g.r.api.remote.entities.RawLoan Trying to set value '3814.0' to an unknown property 'annuity'. Indicates an unexpected API change.
0|roboz    | 12:48:17.725 INFO  c.g.r.api.remote.entities.RawLoan Trying to set value '202' to an unknown property 'premium'. Indicates an unexpected API change.
0|roboz    | 12:48:17.726 INFO  c.g.r.api.remote.entities.RawLoan Trying to set value '3814.0' to an unknown property 'annuityWithInsurance'. Indicates an unexpected API change.
0|roboz    | 12:48:17.971 WARN  c.g.r.api.remote.enums.Region Received unknown loan region from Zonky: ''. This may be a problem, but we continue.

0|roboz    | 12:48:19.891 INFO  c.g.r.a.r.entities.RawInvestment Trying to set value '0.0799' to an unknown property 'revenueRate'. Indicates an unexpected API change.
0|roboz    | 12:48:21.208 WARN  c.g.r.api.remote.enums.Region Received unknown loan region from Zonky: ''. This may be a problem, but we continue.
0|roboz    | 12:48:22.441 WARN  c.g.r.api.remote.enums.Region Received unknown loan region from Zonky: ''. This may be a problem, but we continue.
`

Is anything I can do about that?

My config file:
`
# Konfigurace strategie vytvořená 5.2.2019 nástrojem natural-strategy-setup verze 809ce19
Tato strategie vyžaduje RoboZonky ve verzi 4.5.0 nebo pozdější.
- Obecná nastavení
Robot má udržovat prázdné portfolio.
Běžná výše investice je 200 až 800 Kč.

- Úprava struktury portfolia
Prostředky v ratingu A++ tvoří 10 % aktuální zůstatkové částky.
Prostředky v ratingu A+ tvoří 19 % aktuální zůstatkové částky.
Prostředky v ratingu A tvoří 30 % aktuální zůstatkové částky.
Prostředky v ratingu B tvoří 25 % aktuální zůstatkové částky.
Prostředky v ratingu C tvoří 12 % aktuální zůstatkové částky.
Prostředky v ratingu D tvoří 4 % aktuální zůstatkové částky.

- Filtrování tržiště
Ignorovat vše, kde: klient je důchodce.
Ignorovat vše, kde: délka přesahuje 30 měsíců.
Prodej participací zakázán.
# ----------------------------------------------------------------------
# Pro budoucí úpravy této strategie vložte následující URL do prohlížeče
# https://robozonky.github.io/konfigurace-strategie/#MTt7ImgiOnsiYSI6MywiYiI6WyIwIl0sImMiOlsxXSwiZCI6WzIwMCw4MDBdLCJlIjpbMl0sImYiOlsxXSwiZyI6W119LCJpIjpbWzAsMF0sWzAsMF0sWzEwLDEwXSxbMTksMTldLFszMCwzMF0sWzI1LDI1XSxbMTIsMTJdLFs0LDRdXSwiaiI6W1syMDAsODAwXSxbMjAwLDgwMF0sWzIwMCw4MDBdLFsyMDAsODAwXSxbMjAwLDgwMF0sWzIwMCw4MDBdLFsyMDAsODAwXSxbMjAwLDgwMF1dLCJrIjp7Im8iOjEsInAiOnRydWUsInEiOnRydWUsInIiOlt7InMiOjIsInQiOnsiQyI6WzRdfSwidSI6e319LHsicyI6MiwidCI6eyJGIjpbMywzMF19LCJ1Ijp7fX1dfSwibCI6eyJtIjowfX0=
`

**Comment by triceo** [comment]
I suggest you look at the link I shared earlier - the messages are explained there as well.

**Comment by adambisek** [comment]
Apologize, now I fully understand. Thanks for quick reply.
