### ISSUE TITLE
Nelze spustit 5.1.1 na raspberry

### ISSUE THREAD

**Issue by shakewell9** [RoboZonky/robozonky#413]
Dobrý den,
nainstaloval jsem 5.1.1 na raspberry a vypadává mi to na hlášku:
pi@raspberrypi:~/RoboZonky/5.1.1 $ ./robozonky-exec.sh
Unrecognized VM option 'ExitOnOutOfMemoryError'
Did you mean 'OnOutOfMemoryError=<value>'?
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

Lze to nějak ošetřit v nastavení? Poslední 5.0.2 fungovala bez problémů...

**Comment by triceo** [comment]
Když napíšete do příkazové rádky `java -version`, co vám to vypíše?

`ExitOnOutOfMemoryError` je standardní přepínač, který by měl v moderní Javě rozhodně být. Takže jsem zvědav, co máte za verzi Javy.

**Comment by ladekladek** [comment]
Ach jo, taky mám Raspberry.
problém stejný.


Javu máme:
java version "1.8.0_65"
Java(TM) SE Runtime Environment (build 1.8.0_65-b17)
Java HotSpot(TM) Client VM (build 25.65-b01, mixed mode)

Jde nainstalovat nová verze Javy na RP?

**Comment by shakewell9** [comment]
To samé co ledekladek

java version "1.8.0_65"
Java(TM) SE Runtime Environment (build 1.8.0_65-b17)
Java HotSpot(TM) Client VM (build 25.65-b01, mixed mode)

**Comment by ladekladek** [comment]
Jo, tak nainstalovat Java 11 na Raspberry jde celkem jednoduše.
A zdá se že to pak funguje v pořádku.

wget https://github.com/bell-sw/Liberica/releases/download/11.0.2/bellsoft-jdk11.0.2-linux-arm32-vfp-hflt.deb

sudo apt-get install ./bellsoft-jdk11.0.2-linux-arm32-vfp-hflt.deb


viz: http://hirt.se/blog/?p=1116

**Comment by triceo** [comment]
Přesně tak - 1.8.0_65 je skoro 4 roky stará. Takže aktualizace rozhodně pomůže.
Tohle zavírám, protože to není chyba na straně robota.

**Comment by v6ak** [comment]
Ona situace s Javou na Raspbianu není ideální:

* Oracle Java 8 tam je fakt dost stará, nevím proč se přestala updatovat. Ale i kdyby se updatovala, teď se už updatovat nebude.
* Viděl jsem tam aktuálnější OpenJDK 8, možná to bude dostávat i updaty po konci podpory od Oracle. Jenže OpenJDK 8 pro ARM je poněkud pomalejší než Oracle JDK. Na jednu stranu RoboZonky mi nepřijde náročné na CPU, na druhou stranu Raspberry taky není kdovíjak výkonné. Tento problém řeší novější OpenJDK (snad už devítka, nejsem si jist).
* Je tu OpenJDK 9. No, možná nějaké patche bude dostávat (i když třeba ne od Oracle), ale…
* Jedenáctka v repozitářích není. Možná bude (podobně jako v Debianu) v testingu.
* Instalovat Liberica JDK jednorázovým stažením vyřeší neaktuálnost jednorázově, ale bez ruční údržby se dostanete časem do podobné situace.

**Comment by triceo** [comment]
@v6ak Nezbývá než doufat, že si ekosystém na rychlejší updatování JDK zvykne. Já nemám v plánu v tomhle směru po migraci na OpenJDK 11 už dělat žádné velké změny - nicméně doby, kdy bylo udržitelné být dekádu na jedné major verzi Javy, prostě skončily. (A mám-li být upřímný, myslím, že je to tak dobře.)

**Comment by v6ak** [comment]
Ještě jsem k Javě na Raspbianu našel, že lze nainstalovat Liberica JDK z repozitářů, což vyřeší updaty: https://bell-sw.com/announcement/2019/03/28/linux-repositories/ Je potřeba místo amd64 zvolit správnou platformu (armhf pro 32b Pi, arm64 pro 64b),

Dále jsem zjistil, že Raspberry Pi 1 není podporované, aspoň zatím: https://github.com/bell-sw/Liberica/issues/1
