### ISSUE TITLE
Oddělené výše investic pro primární a sekundární trh

### ISSUE THREAD

**Issue by adambisek** [RoboZonky/robozonky#422]
Dobrý den,
děkuji za váš čas, který Robotonky věnujete.

Je možné nějak odděleně nastavit výše investice pro primární a sekundární trh?

Jde totiž o to, ze na primárním trhu chci investovat vždy jen 200 Kč.
Na sekundárním trhu za určitých podmínek akceptuji rád participace do 400 Kč.

Pokud robota nastavím na výši investice 200-400, sekundární trh se investuje správně. Ale na primárním trhu investuje maximum co může, tzn 400 Kč.

Je to možné nějakým způsobem nastavit?

**Comment by triceo** [comment]
Zdravím. V tuhle chvíli to nijak nastavit nejde. Ale odložím si to tu, třeba to někdy dodělám.

**Comment by adambisek** [comment]
Děkuji. Pro vysvětlení účelu ještě zmínim, ze samo Zonky uvadi, ze po prvním roce splacení statisticky významné klesá rizikovost půjčky. Muže tedy jít o zajímavý zdroj rizikovejsich půjček, bez nutnosti investovat ty úplně nejmenší částky.
