### ISSUE TITLE
robozonky.cli a 2FA

### ISSUE THREAD

**Issue by SonGokussj4** [RoboZonky/robozonky#459]
Možná mi něco nedochází, ale jak do robozonky.cli hodím nově vygenerované 2FA heslo?
Používám jako Docker.
Z textu, cituji _"Do 10 minut od získání autorizačního kódu jej musíte zadat buď do instalátoru RoboZonky, **nebo přímo do souboru robozonky.cli** v již existující instalaci."_ toho nejde moc poznat.

Děkuji. Jinak super práce!

**Comment by triceo** [comment]
@SonGokussj4 Zdravím. Zatím to není implementované. _RoboZonky 5.4.0_ koncem měsíce to bude mít vyřešené. Vydržte - _RoboZonky 5.3_ zatím funguje.

**Comment by jirislav** [comment]
Není toto issue již hotové díky [Wiki stránce: 2FA a RoboZonky](https://github.com/RoboZonky/robozonky/wiki/2FA-a-RoboZonky) ?

**Comment by jirislav** [comment]
@triceo mohl byste prosím upravit [release notes verze 5.4.0](https://github.com/RoboZonky/robozonky/releases/tag/robozonky-5.4.0-cr-1) tak, aby obsahovaly odkaz na 2FA Wiki stránku? Mám takový pocit, že bez toho to človek nerozjede :)

**Comment by triceo** [comment]
Díky, upravil jsem to. Ostrá verze bude někdy příští týden, pak tuhle issue zavřu.

**Comment by jirislav** [comment]
> Díky, upravil jsem to. Ostrá verze bude někdy příští týden, pak tuhle issue zavřu.

Skvělé, díky, snad díky tomu bude přechod pro další snadnější.
