### ISSUE TITLE
Token nepřežije restart robota

### ISSUE THREAD

**Issue by triceo** [RoboZonky/robozonky#461]
Pokud po startu robota dojde k refreshi autentizačního tokenu, robot po ukončení nejspíše už nenastartuje. Je to proto, že nový token se nikam neuloží.

**Comment by mark-stopka** [comment]
Neměl by ideálně robot nový token vždycky zapsat do robozonky.keystore po každém refreshi?

**Comment by triceo** [comment]
Měl. A to právě nedělá.

**Comment by mark-stopka** [comment]
@triceo, jo, šlo mi jen o to si ujasnit kam by ho měl ukládat :-), to že to nedělá mi došlo z textu issue...
