### ISSUE TITLE
Distribuovat JRE s RoboZonky

### ISSUE THREAD

**Issue by triceo** [RoboZonky/robozonky#476]
Nainstalovat Javu je pro spoustu uživatelů, zejména na Windows, zásadní problém. Zároveň, když už jí nainstalují, je problém jí upgradovat. Měli bychom ji tedy dodávat společně s robotem.

**Comment by kalmir** [comment]
Jednodušším dočasným řešením by mohl být krátký návod. Čerstvá zkušenost lama+ uživatele (moje) na Win: nainstalovat Java, jasný, google, výsledek JRE 8, instalace nejde, fóra, aha bude to verzí, zvláštní t o číslování verzí, proč instalace 13 nezabrala?, fóra, googlení, aha pes bude zakopám v environment variables, zkusím tohle, nefunguje, další fidlení... a tadá!

**Comment by triceo** [comment]
@kalmir Jako krátkodobé řešení určitě. Z dlouhodobého hlediska bych ten problém rád prostě odstranil.

**Comment by panther7** [comment]
@kalmir Přesně tohle jsem řešil minulý týden. Díky absenci "krátkého návodu" jsem prošel všemi kroky. Jen nerozumím proč Oracle má poslední JRE ve verzi 8.

**Comment by triceo** [comment]
@panther7 Oracle změnil business model. Jejich Java už je nově dostupná pouze komerčně.

Oficiální nekomerční Java je OpenJDK, kde je garantováno, že je 100 % kompatibilní s Oracle JDK. A OpenJDK můžete získat z mnoha zdrojů - z velkých jmen třeba projekt AdoptOpenJDK, Red Hat, Azul...

**Comment by adambisek** [comment]
A bude varianta i bez JRE? Někdy si totiz potrebuju nainstalovat vlastní verzi Javy, obzvlášť, když Robozonky bezi na ARM procesoru.

**Comment by triceo** [comment]
@adambisek Jo, to nebude problém. S příchodem Javy 14 se tomu začnu věnovat, některé věci tam budou výrazně jednodušší než dnes.

**Comment by triceo** [comment]
První vlaštovka: #515.
