### ISSUE TITLE
Nejde spustit na posledním dostupném JRE

### ISSUE THREAD

**Issue by panther7** [RoboZonky/robozonky#478]
https://www.java.com/en/download/

```
java -jar robozonky-distribution-cli-5.5.0-full.jar
java.lang.UnsupportedClassVersionError: com/github/robozonky/cli/Main has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main"
```

* java: 1.0.8_231
* windows: 10 (1909)

**Comment by mark-stopka** [comment]
java -jar <jar>
--
Best regards / S pozdravem,
BSc. Mark Stopka, BBA

**Comment by panther7** [comment]
> java -jar <jar> -- Best regards / S pozdravem, BSc. Mark Stopka, BBA

 I tak...

Nejde spustit ani ze zipu (robozonky-distribution-full-5.5.0.zip), log:
```
$ ./robozonky.sh
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
Unrecognized option: --module-path
```

**Comment by panther7** [comment]
Hm, nejde spustit na posledním dostupném JRE (https://www.java.com/en/download/), nutno stáhnout Java SDK.

**Comment by triceo** [comment]
@panther7 Chyba, kterou ukazujete, je způsobena tím, že robota spouštíte na Javě 8. Vzhledem k tomu, že vidím nějaký UNIX, půjde o chybě nastavenou `JAVA_HOME`, která stále ukazuje na Java 8.

V každém případě nejde o chybu robota.

**Comment by triceo** [comment]
(Na UNIX usuzuji podle souboru `robozonky.sh`. Pokud jde o Windows, tak je problém pořád stejný - Java 8 - ale řešení jiné. Konkrétně je ve windows potřeba změnit PATH, aby ukazovala na novou Javu.)

**Comment by panther7** [comment]
Škoda, že není podporována JRE 8, novější Oracle ani nemá a že je nutné pro spuštění SDK.
Na NASu, kde bych si to chtěl rozjet, podporuje jen javu JRE/SDK 8.
Moje pokusy byly na Windows, kde jsem pro úspěšné spuštění musel nainstalovat SDK 13.

**Comment by triceo** [comment]
Novější JDK je nově dostupná hned na několika místech. (Oracle už poskytuje pouze komerční.)
Např. tady: https://adoptopenjdk.net/

Co se NASu týká... Jo, zrovna Synology na to kašle. Ale odmítám kvůli jedný firmě zůstávat v pravěku. Moderní Java je dostupná na všech myslitelných platformách s výjimkou Synology a pro Synology se dá RoboZonky zprovoznit třeba v Dockeru, viz tady:

https://github.com/RoboZonky/robozonky/wiki/Docker--a-Synology

**Comment by panther7** [comment]
Hm, ok, jinak NAS není Synology, ale QNAP, evidětně je těch značek více.

Díky

**Comment by SpiReCZ** [comment]
@panther7 @triceo Vím, že se jedná o offtopic, nicméně jsem začal pracovat na: https://github.com/SpiReCZ/adoptopenjdk-synology, k dispozici je preview build.

**Comment by panther7** [comment]
@SpiReCZ Ahoj, již nějakou dobu používám: https://github.com/rednoah/java-installer
Obsahuje i qpkg balíček, který se používá v Qnapu a funguje dobře.

**Comment by SpiReCZ** [comment]
@panther7 Díky znám, vypadá celkem dobře.

**Comment by SpiReCZ** [comment]
Btw: java-installer od rednoah se neumi spravne odinstalovat. Pak tam zustanou napriklad broken symlinky. To jen at vite, co instalujete.

**Comment by panther7** [comment]
@SpiReCZ Aha, díky za info, ale s problémem se nesetkal a asi v nejbližší době nebudu odinstalovat. :)

Jinak pokud víš balíček bude fungovat i v QNAP, tak proč ne.

**Comment by SpiReCZ** [comment]
@panther7 Zatím jsem o tom nepřemýšlel. Jediné co tomu asi brání je to, že takové zařízení nevlastním. A o možnosti prostředí virtualizovat nevím.
