### ISSUE TITLE
Instalátor hodí chybu při vložení url konfigurace strategie

### ISSUE THREAD

**Issue by panther7** [RoboZonky/robozonky#479]
```
WARNING: Validation using com.github.robozonky.installer.UrlValidator failed: org.picocontainer.PicoCompositionException: Either the specified parameters do not match any of the following constructors: [com.github.robozonky.installer.UrlValidator()]; OR the constructors were not accessible for 'com.github.robozonky.installer.UrlValidator'
```

Java: 13.0.1
Windows: 10 (1909)

**Comment by panther7** [comment]
Nejde ani vybrat ze souboru, s hláškou, že nefunguje nebo není platná (vygenerováno z webu)

**Comment by triceo** [comment]
Díky, prozkoumám to.

**Comment by panther7** [comment]
Už jsem vypozoroval, čím to by je, pousouváním portfolia, došlo k zaokrouhlení procent, takže to vycházelo (plácnu, 100,4%), pak ta url byla nevadliní, i když webovka se tvářila OK

**Comment by triceo** [comment]
@panther7 Máte odkaz na strategii, která je takhle chybná? Budeme to každopádně chtít opravit.

**Comment by panther7** [comment]
@triceo Ano, je to: https://robozonky.github.io/konfigurace-strategie/#NDt7ImkiOltbMywzXSxbMTMsMTNdLFsxOSwxOV0sWzIxLDIxXSxbMTksMTldLFsxMSwxMV0sWzcsN10sWzUsNV0sWzIsMl0sWzEsMV0sWzAsMF1dLCJoIjp7ImEiOjMsImIiOlsiMCJdLCJjIjpbMV0sImQiOlswLDIwMF0sImUiOlsyXSwiZzEiOjF9LCJqIjpbWzAsMjAwXSxbMCwyMDBdLFswLDIwMF0sWzAsMjAwXSxbMCwyMDBdLFswLDIwMF0sWzAsMjAwXSxbMCwyMDBdLFswLDIwMF0sWzAsMF0sWzAsMF1dLCJrIjp7Im8iOjEsInAiOnRydWUsInEiOnRydWUsInIiOlt7InMiOjIsInQiOnsiRiI6WzMsMTNdfSwidSI6e319XX0sImwiOnsibSI6MH19

**Comment by triceo** [comment]
@jhrcek Můžeš na to ve volné chvíli mrknout, prosím?

**Comment by jhrcek** [comment]
@triceo Zajimavé. Našel jsem kroky jak problém zreprodukovat:
1. začít s novou strategií
2. v sekci struktura portfolia (kde je zezačátku vybráno konzervativní portfolio) kliknout na posuvník vedle 2.99 % (nástroj to registruje jako změnu posuvníku a přepne z konzervativní -> mnou definované). Stejného dosáhnu i např tím, že přetáhnu první posuvník a vrátím ho na výchozi hodnotu.

Aktuální chování:
Takto definovaná strategie je nevalidní, protože dojde k zaokrouhlení 1.5 -> 2 a 0.5 -> 1, čímž je dosaženo součtu 101, ale validační logika to z někajého důvodu neregistruje jako chybu. ALE strategie jde exportovat a její obnovou z url nastave výše uvedený problém.

Očekávané chován:
po kliku popsaném v kroku 2 výše změníme portfolio na uživatelem definované, ALE validace správně zachytí změnu a korektně nahlásí součet 101, čímž přinutíme uživatele k opravě součtu minim a zabráníme exportu invalidní strategie. @triceo souhlasíš, že takto by se to mohlo chovat?
Pokud si dobře pamatuju, dohodli jsme se na tom, že posuvníky umožní nastavovat jen s přesností na celá procenta. 0.5 a 1.5 procent jsou zadrátované hodnoty u předdefinovaných portfolií, ale v momentě, kdy změníme na uživatelem definované, měl by nástroj přepnout všechny posuvníky na integer-only hodnoty.

Chybu opravím v průběhu následujícího týdne. @panther7 pokud nechcete na opravu čekat, doporučuji obnovit strategii z URL, opravit strategii ručně a znovu exportovat. A raději než nastavovat 
```
- Výše investice
S úročením 15,49 % p.a. jednotlivě investovat 0 Kč.
S úročením 19,99 % p.a. jednotlivě investovat 0 Kč.
```
(z čehož usuzuji, že nechcete vůbec investovat do půjček s nejvyšším úročením), bych nastavil dolní i horní hranici u půjček s tímto úročením ve struktuře portfolia, jako na obrázku

![Screenshot from 2019-11-24 14-00-25](https://user-images.githubusercontent.com/2716069/69495058-17448700-0ec3-11ea-9df7-2786910e825a.png)

**Comment by panther7** [comment]
@jhrcek Díky za návrh řešení, ale to byly to jen pokusy, portfolio jsem si již nastavil podle sebe.

**Comment by triceo** [comment]
@jhrcek Já přemýšlím, jestli to nové chování, jak ho popisuješ, je ideální. Z validní strategie ("konzervativní") se stane nevalidní jen tím, že přepneš na "mnou definované". 

Jako lepší řešení mi přijde začít podporovat kroky po 0,5 %. (Když jsme zaváděli ta celá procenta, nic jako půl-procenta ještě neexistovalo. S tím přišli na Zonky až později.) Zároveň jít pod 0,5 % už mi přijde jako overkill. Nicméně jak nad tím přemýšlím dál, přijde mi, že 0,5 % už je příliš titěrný krok pro to UI. 

Tak si říkám, jestli bychom nemohli 0,5 % kroky prostě podporovat "pod povrchem", ale ty slidery pořád umožnit posouvat jen po 1 %. Napadá mě jedna nevýhoda, a to že při přechodu z "konzervativní" do "mnou definované" by se ten slider dostal do stavu, do kterého už se nikdy nedokáže vrátit. Ale v tom nevidím zas tak velký problém.

**Comment by jhrcek** [comment]
@triceo ok, popřemýšlel jsem nad tím, a myslím, že tvůj návrh dává lepší smysl než mnou navržené zaokrouhlování. Už teď robot podporuje desetinné čísla ve struktuře portfolia, takže můžu udělat to, co říkáš: jakmile se uživatel dotkne sliderů, přepnu na uživatelem definované (jako do teď), s tím rozdílem, že do strategie se vyrenderují ty 1,5 a 0,5 procenta, ale zároveň umožním pouze kroky po celých procentech. Takže když uživatel sáhne na ty půlprocenta, tak to poskočí na nejbližší celé procento a už to neumožní se vrátit na půlprocenta.

**Comment by triceo** [comment]
Nová verze _RoboZonky_ vč. nového konfiguračního nástroje vyjde již brzy. 
Díky za report!
