### ISSUE TITLE
Problém se změnou strategie od v5.6.0

### ISSUE THREAD

**Issue by panther7** [RoboZonky/robozonky#483]
**Edit:** Viz druhý příspěvek

~~Zdravím, právě mi robot přihodil na investici, která by neměla splňovat tuto podmínku:
`Ignorovat úvěr, kde: úrok přesahuje 10,99 % p.a.; délka přesahuje 15 měsíců.`~~

* ~~[Investice](https://app.zonky.cz/loan/617064)~~
* ~~[Strategie](https://robozonky.github.io/konfigurace-strategie/#NDt7ImkiOltbMCwwXSxbMTQsNzBdLFsyMCw3NV0sWzIyLDgwXSxbMjAsNzVdLFsxMiw2MF0sWzcsNTBdLFs0LDI1XSxbMSw1XSxbMCwwXSxbMCwwXV0sImgiOnsiYSI6MywiYiI6WyIwIl0sImMiOlsxXSwiZCI6WzAsMjAwXSwiZSI6WzJdLCJnMSI6MH0sImoiOltbMCwyMDBdLFswLDIwMF0sWzAsMjAwXSxbMCwyMDBdLFswLDIwMF0sWzAsMjAwXSxbMCw0MDBdLFswLDQwMF0sWzAsMjAwXSxbMCwyMDBdLFswLDIwMF1dLCJrIjp7Im8iOjEsInAiOnRydWUsInEiOmZhbHNlLCJyIjpbeyJzIjowLCJ0Ijp7IkoiOnsidiI6MywidyI6NX0sIkYiOlszLDE1XX0sInUiOnt9fSx7InMiOjAsInQiOnsiRiI6WzMsMjVdfSwidSI6e319XX0sImwiOnsibSI6MH19)~~

Robozonky v5.6.0-cr-1

**Comment by panther7** [comment]
Už jsem na to přišel, po migraci na 5.6.0, jsme změnil ručně strukturu portofila.
```
Prostředky úročené ... % p.a. mají tvořit ... až ... % aktuální zůstatkové částky.
// Nově tato formulace zní:
Prostředky úročené ... % p.a. mají tvořit ... % aktuální zůstatkové částky.
```
Pochopil jsem, že spodní hranice nefunguje, tudíž jsme změnil:
```
Prostředky úročené 3,99 % p.a. mají tvořit 14 až 70 % aktuální zůstatkové částky.
// na
Prostředky úročené 3,99 % p.a. mají tvořit 70 % aktuální zůstatkové částky.
```
Pak se portofilo nenačte a tudíž nefungovalal strategie.

**Comment by panther7** [comment]
Zajímavé je, že v logu je:
```
WARN  Portfolio share for rating AAAAA gives a range of <0.14000000; 0.70000000>. The minimum has been deprecated and will be ignored. Please update your strategy.
```
Což splňuje mojí teorii, odmazat spodní hranici, bohužel pak taková strategie nefunguje...

**Comment by triceo** [comment]
Teď tomu nerozumím. Robot investuje jen tehdy, pokud se strategie úspěšně načetla. Takže provedená investice je důkazem, že strategie se načetla - předpokládám tedy, že se načetla i bez té spodní hranice.

**Comment by panther7** [comment]
> Teď tomu nerozumím. Robot investuje jen tehdy, pokud se strategie úspěšně načetla. Takže provedená investice je důkazem, že strategie se načetla - předpokládám tedy, že se načetla i bez té spodní hranice.

Olouvám se za zmatky, issue jsme upravil, nyní to je relevantní od druhého příspevku

**Comment by triceo** [comment]
Na _RoboZonky 5.6.0-cr-1_ se mi problém nedaří nasimulovat. Obě verze strategie (jak stará, tak nová) bez potíží fungují.

**Comment by panther7** [comment]
Hm, máte pravdu, nevím jak jsem se dostal do stavu, kdy to nefungovalo. Díky
