### ISSUE TITLE
Přihazování do investice, ikdyž není splněna podmínka

### ISSUE THREAD

**Issue by panther7** [RoboZonky/robozonky#484]
Oživuji problém, pro který původně vzniklo issue #483

Robot přihazuje i když by neměl, konkrétně na [investici, která má splatnost 19 měsíců](https://app.zonky.cz/loan/614099).
Ve [strategii](https://robozonky.github.io/konfigurace-strategie/#NDt7ImkiOltbMCwwXSxbMTQsNzBdLFsyMCw3NV0sWzIyLDgwXSxbMjAsNzVdLFsxMiw2MF0sWzcsNTBdLFs0LDI1XSxbMSw1XSxbMCwwXSxbMCwwXV0sImgiOnsiYSI6MywiYiI6WyIwIl0sImMiOlsxXSwiZCI6WzAsMjAwXSwiZSI6WzJdLCJnMSI6MH0sImoiOltbMCwyMDBdLFswLDIwMF0sWzAsMjAwXSxbMCwyMDBdLFswLDIwMF0sWzAsMjAwXSxbMCw0MDBdLFswLDQwMF0sWzAsMjAwXSxbMCwyMDBdLFswLDIwMF1dLCJrIjp7Im8iOjEsInAiOnRydWUsInEiOmZhbHNlLCJyIjpbeyJzIjowLCJ0Ijp7IkoiOnsidiI6MywidyI6NX0sIkYiOlszLDE1XX0sInUiOnt9fSx7InMiOjAsInQiOnsiRiI6WzMsMjVdfSwidSI6e319XX0sImwiOnsibSI6MH19) je následující podmínka:
`Ignorovat úvěr, kde: úrok přesahuje 10,99 % p.a.; délka přesahuje 15 měsíců.`

Robozonky v5.5.0

**Comment by triceo** [comment]
Můžu vidět log z této doby, prosím?

**Comment by panther7** [comment]
@triceo Jasně, [robozonky.20191129.zip](https://github.com/RoboZonky/robozonky/files/3905415/robozonky.20191129.zip)

**Comment by triceo** [comment]
Pokud vidím správně, tak úrok u zmiňované půjčky je 10,99 % p. a.
Vaše strategie říká `úrok přesahuje 10,99 % p.a.`.

Úvěr nepřesahuje 10,99 %, takže není ignorován. Žádnou chybu nevidím.

(Problém bude možná jinde. Místo `;` v tom pravidle si představte logickou spojku "A ZÁROVEŇ"  a snad už bude jasnější, proč se to chová tak, jak se to chová.)

**Comment by panther7** [comment]
Problém je tedy v generátoru strategie, viz screenshot.

**Comment by panther7** [comment]
^ @triceo

**Comment by triceo** [comment]
Ani tady žádný problém nevidím. Nastavení vlevo zcela odpovídá tomu, co se objevilo napravo. (Nebo jsem slepý.)

Máte dvě pravidla. Vámi zmíněná půjčka ani jednomu z nich neodpovídá. Zkusme to jinak - na základě čeho si myslíte, že se ta půjčka měla ignorovat?

**Comment by panther7** [comment]
Robot přihodil na nabídku 10,99% na dobu 19 měsíců, podmínka níže jasně říká, že by se to mělo ignorovat.

"Ignorovat úvěr, kde: úrok přesahuje 10,99 % p.a. a zároveň délka přesahuje 15 měsíců."

**Comment by triceo** [comment]
Podmínka jasně říká, že úrok musí **přesahovat** 10,99 % p.a.
Úvěr měl 10,99 % p.a., tedy **se rovnal**, nikoliv **přesahoval**.

**Comment by panther7** [comment]
Jo, dement, díky, upraveno na:
`Ignorovat úvěr, kde: úrok je 10,99 až 19,99 % p.a. a zároveň délka přesahuje 15 měsíců.`
