### ISSUE TITLE
Unify terminology in natural strategy parser: úvěr vs. půjčka

### ISSUE THREAD

**Issue by jhrcek** [RoboZonky/robozonky#499]
As far s I know, úvěr a půjčka are synonyms. However using both of them in natural language strategy config might lead to confusion. It might be unclear whether they mean exactly the same or if there's some difference. I think it might be clearer to use just one of the two in all places in the parser. @triceo What do you think? Feel free to close this if you don't think it would improve anything.

Here are the places where these two are used. 
```bash
robozonky-robozonky-strategy-natural/src/main/antlr4> grep -ri 'úvěr' --color
imports/MarketplaceFilters.g4:    'Ignorovat úvěr, kde: ' r=primaryMarketplaceFilterConditions { $result.when($r.result); }
imports/Defaults.g4:    'Robot má investovat do úvěrů po ' amount=intExpr KC '.' { $result = $amount.result; }
imports/Defaults.g4:    ' % výše úvěru' DOT
imports/InvestmentSize.g4:    'Do úvěrů s úročením ' r=interestRateBasedRatingExpression 'investovat po ' i=intExpr KC DOT {


/robozonky/robozonky-strategy-natural/src/main/antlr4> grep -ri 'půjč' --color
imports/MarketplaceFilters.g4:        'Ignorovat všechny půjčky.' { $enabled = false; }
imports/MarketplaceFilters.g4:        'Investovat do všech půjček.' { $enabled = true; }
imports/Tokens.g4:PURPOSE_REFINANCING             : 'refinancování půjček';
imports/Defaults.g4:        'Robot má pravidelně kontrolovat rezervační systém a přijímat rezervace půjček odpovídajících této strategii.' {
imports/Defaults.g4:        'Robot má převzít kontrolu nad rezervačním systémem a přijímat rezervace půjček odpovídajících této strategii.' {
com/github/robozonky/strategy/natural/NaturalLanguageStrategy.g4:            'Ignorovat všechny půjčky i participace.' {
com/github/robozonky/strategy/natural/NaturalLanguageStrategy.g4:            'Investovat do všech půjček a participací.'
```

**Comment by triceo** [comment]
That's a good point. Now the question is... how to do that without breaking backwards compatibility too much?

**Comment by jhrcek** [comment]
You could leave that for the next time when you're doing more backward incompatible changes to strategy config. Or you could close it as it's not that important :)

**Comment by triceo** [comment]
Well, one thing I *can* do now is to change the phrasing in places where I'm making changes in 5.7.0, so:

    imports/Defaults.g4:    'Robot má investovat do úvěrů po ' amount=intExpr KC '.' { $result = $amount.result; }
    imports/Defaults.g4:    ' % výše úvěru' DOT
    imports/InvestmentSize.g4:    'Do úvěrů s úročením ' r=interestRateBasedRatingExpression 'investovat po ' i=intExpr KC DOT {

**Comment by triceo** [comment]
But I would only be able to do that in CR1, so for now, the tool should still support the old wording. So that the testers can test the strategy tool together with Beta 1.
