### ISSUE TITLE
WARN  Received unknown value from Zonky: ''. This may be a problem, but we continue.

### ISSUE THREAD

**Issue by liry** [RoboZonky/robozonky#509]
Dnes jsem začal dostávat hlášky:
```
WARN  Received unknown value from Zonky: ''. This may be a problem, but we continue.
```
Začalo to v 10:24 (9 minut po poslední investici, možná to souvisí s tím, že na další investici teď na účtu není dost prostředků).

**Comment by triceo** [comment]
@liry To máte docela štěstí, hromadě lidí robot už druhý den vůbec nefunguje. Zonky má nějaký problém s API. Řešíme to, chyba nebude v robotu.

**Comment by liry** [comment]
@triceo tak ted uz tam mam penize a taky mi robot nefunguje ... na foru jsem zadnou informaci o nefunkcnim API nenasel, maji nekde nejaky verejny support ticket, ci tak neco?

**Comment by triceo** [comment]
@liry O ničem takovém nevím. Když na něco přijdeme, píšeme jim to buď do privátního mailing listu pro vývojáře třetích stran, nebo na Facebook.
