### ISSUE TITLE
Návrh: Lepší přenositelnost spouštěče

### ISSUE THREAD

**Issue by panther7** [RoboZonky/robozonky#528]
Zdravím, chtěl bych si převést robozonky z Windows na Linux (debian), aniž bych musel dělat celou konfiguraci. Prostě bych zkopírovat všechny soubory z Windows a spustil na Linuxu. Buhužel robozonky-exec obsahuje absolutní cesty. Bylo by možné naučit instalátor, aby změnil jen robozonky-exec po přemístění do jiné složky/systému?

**Comment by panther7** [comment]
Bohužel jsme si robozonky-exec.sh na Woknech smazal (protože enbyl potřeba), kdybych ho měl, tak bych si v něm cesty změnil. V mém případě by stačilo mít nějaký "defaultní" robozonky-exec.sh

**Comment by triceo** [comment]
Zdravím, předně se omlouvám za opožděnou odpověď, nějak mi to zapadlo.
V tuhle chvíli nevím, jestli je to možné aniž bych musel měnit velkou spoustu věcí, ale zamyslím se nad tím.
