### ISSUE TITLE
java binárka nainstalovaná instalátorem není executable 

### ISSUE THREAD

**Issue by jhrcek** [RoboZonky/robozonky#540]
Instaloval jsem latest 6.0.0-beta-3 pomocí instalátoru https://github.com/RoboZonky/robozonky/releases/download/robozonky-6.0.0-beta-3/robozonky-installer-6.0.0-beta-3-linux-x64.tar.xz
Robozonky nainstalovaný tímto způsobem nešel spustit. Viz poslední řádek: java nemá executable oprávnění. 

```
~> cd ~/RoboZonky/6.0.0-beta-3
~/RoboZonky/6.0.0-beta-3> ./robozonky.sh
/home/jhrcek/RoboZonky/6.0.0-beta-3/Dist/robozonky.sh: line 25: /home/jhrcek/RoboZonky/6.0.0-beta-3/Dist/jre/bin/java: Permission denied
/home/jhrcek/RoboZonky/6.0.0-beta-3/Dist/robozonky.sh: line 25: exec: /home/jhrcek/RoboZonky/6.0.0-beta-3/Dist/jre/bin/java: cannot execute: Permission denied
Will run 'robozonky-app-6.0.0-beta-3-full.jar' from '/home/jhrcek/RoboZonky/6.0.0-beta-3/Dist'.
Will use '/home/jhrcek/RoboZonky/6.0.0-beta-3/Dist/jre/bin/java' as the Java executable.
~/RoboZonky/6.0.0-beta-3> ls -alsh /home/jhrcek/RoboZonky/6.0.0-beta-3/Dist/jre/bin/java
 16K -rw-r--r--. 1 jhrcek jhrcek  13K May 29 22:08 java
```

`chmod +x` to spravil

Ještě by mě zajímalo jak si lokálně zbuildit nový instalátor?
Doteď když jsem si chtěl zbuildit instalátor z masteru, tak jsem mohl udělat:
```bash
mvn clean package -DskipTests
INSTALLER=$(find -iname 'robozonky-installer*full.jar')
java -jar $INSTALLER
```
Ale to mi teď házi chybu:
```
java -jar $INSTALLER
Error: Could not find or load main class null
Caused by: java.lang.ClassNotFoundException: null
```

Předem díky za odpověď :smiley:

**Comment by triceo** [comment]
Tu spustitelnost opravím, díky za report. (Bude potřeba přímo v instalátoru ta práva nastavit.)
Co se týká buildování, spustitelný instalátor je pořád ve stejném modulu, nicméně místo na `-full.jar` končí na `-noarch.jar`.

**Comment by triceo** [comment]
Sluší se ale poznamenat, že cokoliv v `robozonky-installer` je meziprodukt. Nebude to mít správně nastavené logování atd. Hotová distribuce instalátoru je až v `robozonky-distribution-installer`.

**Comment by jhrcek** [comment]
Díky, beru na vědomí :+1:
