### ISSUE TITLE
Suggest: Neomezená struktura portfolia

### ISSUE THREAD

**Issue by panther7** [RoboZonky/robozonky#551]
Možnost říci robotovi, aby k přihazování nepoužíval procentuální portfolio (a prostě přihazoval).

**Comment by mark-stopka** [comment]
To již lze takto, stačí doplnit ostatní ratingy:
```
Prostředky úročené 13,49 % p.a. mají tvořit 100 % aktuální zůstatkové částky.
Prostředky úročené 15,49 % p.a. mají tvořit 100 % aktuální zůstatkové částky.
```

**Comment by panther7** [comment]
Jakože vše nastavit na `100%`?

**Comment by mark-stopka** [comment]
Ano.

**Comment by panther7** [comment]
Dobře, tím pádem by mohla být ve webovém rozhraní volba, která to všechno na 100% nastaví ;-)

**Comment by triceo** [comment]
Mohla, ale nebude. Touhle volbou prakticky říkáš "je mi úplně jedno, co mi skončí v portfoliu." A já nevěřím tomu, že to někdo skutečně chce takhle říct. (Když bude celý portfolio 19,99 % p.a., je to OK? Když bude celý portfolio 2,99 % p. a., je to OK? Tahle strategie v tom nedělá rozdíly.)

Jasně, dalo by se spekulovat, že může následovat sada desítek a stovek filtrů, které očekávané portfolio určí velice přesně. Dalo by se spekulovat, že žádná z výše popsaných situací nemůže nastat. Nicméně já svojí roli v tomhle případě chápu jinak.

V robotu ta možnost je, viz nastavení výše. Pokročilý uživatel si jí najde. Ale to neznamená, že střelbu do vlastních nohou budu zjednodušovat náhodným kolemjdoucím. :-) Snad je to takhle jasnější.

**Comment by panther7** [comment]
Jasně, díky :-)
