### ISSUE TITLE
Podpora proxy serveru

### ISSUE THREAD

**Issue by fofo76** [RoboZonky/robozonky#552]
Bylo by možné implementovat podporu proxy serveru? V současné době aplikace předpokládá pouze direct konektivitu.
Děkuji
FoFo76

**Comment by triceo** [comment]
Podpora pro proxy je zabudovaná přímo v Javě:
https://docs.oracle.com/javase/8/docs/technotes/guides/net/proxies.html

Zmíněné systémové properties je pak potřeba přidat do `robozonky-exec*` souboru, nebo do proměnné prostředí `JAVA_OPTS` při spouštění robota.
