### ISSUE TITLE
Každých pár dnů: Fatal error has been detected by the Java Runtime Environment

### ISSUE THREAD

**Issue by Kara-Ro** [RoboZonky/robozonky#582]
Zdravím,
Celou dobu, co používám Robozonky (více než půl roku) se potýkám s nestabilitou. Každých několik dnů se program ukončí (viz. error.log) a musím znovu program spustit a občas dokonce restartovat hardware. 

Používám Raspberry Pi 3 Model B a postupně jsem přecházel na nejnovější verze Robozonky od verze 5.6.0. Dnes jsem přešel na verzi 6.3.0. Používám verzi bez Javy a v Raspberry mám nyní: OpenJDK Runtime Environment (11.0.9.1+1) (build 11.0.9.1+1-post-Raspbian-1deb10u2.) Také jsem už zkoušel Java environment kompletně přeinstalovat. 

Zkoušel jsem i radu poskytnutou errorovou hláškou: "No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again"

Asi před dvěma měsíci jsem začal na jednom Raspberry provozovat dvě nezávislé instance Robozonky a připadá mi, že obě používají stejný "robozonky.log," také se mi zdá, že množství "DEBUG" logů je značný. Nejsem přesvědčen, že toto je důvod proč se Robozonky hroutí, protože stejný problém jsem měl i dříve, ale rád bych zkusil aby každá instance logovala do separátního souboru a také omezit množství zapisovaných dat. 

Vím, že si za problémy můžu převážně tím, že chci Robozonky provozovat na Raspberry, ale budu vděčný za jakoukoli radu a nebo nápad. Možná je problém jen v množství paměti alokované pro Java prostředí, ale zatím jsem moc důkladně nehledal, jak to otestovat
[hs_err_pid28684.log](https://github.com/RoboZonky/robozonky/files/5873345/hs_err_pid28684.log)
.

**Comment by triceo** [comment]
Je tady toho víc najednou, takže začnu tím hlavním - chyba, kterou popisuješ, je někde hluboko unvitř JVM. Robot jí asi nějak způsobil, ale nemám nejmenší tušení čím, ani jak bych to ladil. Na tohle nemám vliv. S trochou štěstí to nějaká příští aktualizace Javy opraví.

Co se týká logování - robot loguje tam, odkud je spuštěn. Pokud spouštíš oba roboty ze stejného adresáře, budou oba logovat do stejného souboru. Dalo by se to asi vyřešit nastavením logovacího souboru v konfiguraci log4j, ale nejlepší je prostě oba roboty spouštět odjinud.

Co se týká toho, co je uvnitř logu - DEBUG logging obsahuje hodně informací, a je to tak záměrně. Slouží k tomu, abych v případě problému dokázal odhalit chybu. Naštěstí je log4j velmi dobře konfigurovatelný - jestli chceš, nemusí logovat vůbec nic. Za cenu toho, že až se objeví v robotu nějaká chyba, nebudu tušit, co se stalo.

Tenhle report zavírám, nemůžu kolem toho nic udělat.

**Comment by Kara-Ro** [comment]
> Je tady toho víc najednou, takže začnu tím hlavním - chyba, kterou popisuješ, je někde hluboko unvitř JVM. Robot jí asi nějak způsobil, ale nemám nejmenší tušení čím, ani jak bych to ladil. Na tohle nemám vliv. S trochou štěstí to nějaká příští aktualizace Javy opraví.
> 
> Co se týká logování - robot loguje tam, odkud je spuštěn. Pokud spouštíš oba roboty ze stejného adresáře, budou oba logovat do stejného souboru. Dalo by se to asi vyřešit nastavením logovacího souboru v konfiguraci log4j, ale nejlepší je prostě oba roboty spouštět odjinud.
> 
> Co se týká toho, co je uvnitř logu - DEBUG logging obsahuje hodně informací, a je to tak záměrně. Slouží k tomu, abych v případě problému dokázal odhalit chybu. Naštěstí je log4j velmi dobře konfigurovatelný - jestli chceš, nemusí logovat vůbec nic. Za cenu toho, že až se objeví v robotu nějaká chyba, nebudu tušit, co se stalo.
> 
> Tenhle report zavírám, nemůžu kolem toho nic udělat.

Děkuji za odpověď a hlavně za nasměrování. Kdyby toto někdo četl a měl podobný problém, tak doporučuji stáhnout built Javy od Azul. Nastavil jsem výchozí Java prostředí na novější verzi než nabízí Raspberry v apt-get rozhraní. Konkrétně jsem použil Zulu13.33+38-CA (build 13.0.4+8-MTS) a od té doby mi Robozonky ani jednou nespadly.
