### ISSUE TITLE
Unable to deserialize property 'datePublished'

### ISSUE THREAD

**Issue by StipaM** [RoboZonky/robozonky#612]
Zdravím. Poslední verze 6.4.1. dnes začala vypisovat do console error: 

_15:59:36.644 ERROR Unable to deserialize property 'datePublished' because of: Error parsing class java.time.OffsetDateTime from value: 1622036990147. Check your @JsonbDateFormat has all time units for class java.time.OffsetDateTime type, or consider using org.eclipse.yasson.YassonConfig#ZERO_TIME_PARSE_DEFAULTING._

Vypisuje se to cca každou vteřinu. Ta hodnota from value je chvíli stejná např: 1622036990147 a pak se změní např. na 1622037688206.

Log file:
[robozonky (2).log](https://github.com/RoboZonky/robozonky/files/6547302/robozonky.2.log)

**Comment by triceo** [comment]
Zdravím. Všiml jsem si toho, i když se mi to neděje rozhodně tak často. Dočasně asi jedině robota vypnout, zatím nemám tušení,co se děje, a oprava bude určitě nejdříve o víkendu.

Díky za report!

**Comment by triceo** [comment]
Jednalo se o chybu na Zonky, která by už měla být odstraněna. Dej vědět, pokud se to ještě vyskytuje.

**Comment by StipaM** [comment]
Zdá se, že už je to pryč.
